CREATE TABLE CITY
(
  City_ID SERIAL PRIMARY KEY,
  City_Name VARCHAR(100) NOT NULL
);

CREATE TABLE TOURIST
(
  Tourist_ID SERIAL PRIMARY KEY,
  First_Name VARCHAR(50) NOT NULL,
  Last_Name VARCHAR(50) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  Phone VARCHAR(20) NOT NULL,
  Language VARCHAR(50),
  Password VARCHAR(50) NOT NULL,
  Birthday DATE NOT NULL,
  User_Name VARCHAR(50) NOT NULL
);

CREATE TABLE COUNTRY
(
  Country_ID SERIAL PRIMARY KEY,
  Country_Name VARCHAR(100) NOT NULL,
  City_ID INT NOT NULL,
  Tourist_ID INT NOT NULL,
  FOREIGN KEY (City_ID) REFERENCES CITY(City_ID),
  FOREIGN KEY (Tourist_ID) REFERENCES TOURIST(Tourist_ID)
);

CREATE TABLE RESTAURANT
(
  Rest_ID SERIAL PRIMARY KEY,
  Rest_Name VARCHAR(100) NOT NULL,
  Address VARCHAR(200) NOT NULL,
  Cuisine_Type VARCHAR(50) NOT NULL,
  Phone_Number VARCHAR(20) NOT NULL,
  Average_Price NUMERIC(6,2) NOT NULL,
  City_ID INT NOT NULL,
  FOREIGN KEY (City_ID) REFERENCES CITY(City_ID)
);

CREATE TABLE BOOKING
(
  Booking_ID SERIAL PRIMARY KEY,
  Booking_Date DATE NOT NULL,
  Num_Of_People INT NOT NULL,
  Status VARCHAR(50) NOT NULL,
  Tourist_ID INT NOT NULL,
  Rest_ID INT NOT NULL,
  FOREIGN KEY (Tourist_ID) REFERENCES TOURIST(TourIST_ID),
  FOREIGN KEY (Rest_ID) REFERENCES RESTAURANT(Rest_ID)
);

CREATE TABLE FEEDBACK
(
  Feedback_ID SERIAL PRIMARY KEY,
  Review_Title VARCHAR(100) NOT NULL,
  Comment TEXT NOT NULL,
  Feedback_Date DATE NOT NULL,
  Tourist_ID INT NOT NULL,
  Rest_ID INT NOT NULL,
  FOREIGN KEY (Tourist_ID) REFERENCES TOURIST(Tourist_ID),
  FOREIGN KEY (Rest_ID) REFERENCES RESTAURANT(Rest_ID)
);

CREATE TABLE RATING
(
  Rating_Type VARCHAR(50) NOT NULL,
  Degree INT NOT NULL,
  Rate_Num INT NOT NULL,
  Feedback_ID INT NOT NULL,
  PRIMARY KEY (Rate_Num, Feedback_ID),
  FOREIGN KEY (Feedback_ID) REFERENCES FEEDBACK(Feedback_ID)
);