DROP TABLE IF EXISTS RATING;
DROP TABLE IF EXISTS FEEDBACK;
DROP TABLE IF EXISTS BOOKING;
DROP TABLE IF EXISTS RESTAURANT;
DROP TABLE IF EXISTS COUNTRY;
DROP TABLE IF EXISTS CITY;
DROP TABLE IF EXISTS TOURIST;