INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (1, 'Afghanistan');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (2, 'Albania');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (3, 'Algeria');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (4, 'Andorra');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (5, 'Angola');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (6, 'Antigua and Barbuda');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (7, 'Argentina');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (8, 'Armenia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (9, 'Australia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (10, 'Austria');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (11, 'Azerbaijan');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (12, 'Bahamas');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (13, 'Bahrain');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (14, 'Bangladesh');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (15, 'Barbados');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (16, 'Belarus');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (17, 'Belgium');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (18, 'Belize');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (19, 'Benin');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (20, 'Bhutan');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (21, 'Bolivia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (22, 'Bosnia and Herzegovina');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (23, 'Botswana');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (24, 'Brazil');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (25, 'Brunei');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (26, 'Bulgaria');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (27, 'Burkina Faso');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (28, 'Burundi');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (29, 'Cambodia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (30, 'Cameroon');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (31, 'Canada');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (32, 'Cape Verde');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (33, 'Central African Republic');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (34, 'Chad');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (35, 'Chile');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (36, 'China');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (37, 'Colombia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (38, 'Comoros');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (39, 'Congo');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (40, 'Costa Rica');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (41, 'Croatia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (42, 'Cuba');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (43, 'Cyprus');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (44, 'Czech Republic');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (45, 'Denmark');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (46, 'Djibouti');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (47, 'Dominica');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (48, 'Dominican Republic');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (49, 'Ecuador');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (50, 'Egypt');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (51, 'El Salvador');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (52, 'Equatorial Guinea');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (53, 'Eritrea');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (54, 'Estonia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (55, 'Eswatini');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (56, 'Ethiopia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (57, 'Fiji');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (58, 'Finland');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (59, 'France');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (60, 'Gabon');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (61, 'Gambia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (62, 'Georgia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (63, 'Germany');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (64, 'Ghana');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (65, 'Greece');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (66, 'Grenada');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (67, 'Guatemala');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (68, 'Guinea');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (69, 'Guinea-Bissau');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (70, 'Guyana');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (71, 'Haiti');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (72, 'Honduras');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (73, 'Hungary');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (74, 'Iceland');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (75, 'India');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (76, 'Indonesia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (77, 'Iran');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (78, 'Iraq');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (79, 'Ireland');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (80, 'Israel');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (81, 'Italy');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (82, 'Jamaica');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (83, 'Japan');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (84, 'Jordan');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (85, 'Kazakhstan');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (86, 'Kenya');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (87, 'Kiribati');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (88, 'Kuwait');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (89, 'Kyrgyzstan');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (90, 'Laos');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (91, 'Latvia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (92, 'Lebanon');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (93, 'Lesotho');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (94, 'Liberia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (95, 'Libya');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (96, 'Liechtenstein');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (97, 'Lithuania');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (98, 'Luxembourg');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (99, 'Madagascar');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (100, 'Malawi');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (101, 'Malaysia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (102, 'Maldives');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (103, 'Mali');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (104, 'Malta');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (105, 'Marshall Islands');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (106, 'Mauritania');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (107, 'Mauritius');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (108, 'Mexico');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (109, 'Micronesia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (110, 'Moldova');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (111, 'Monaco');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (112, 'Mongolia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (113, 'Montenegro');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (114, 'Morocco');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (115, 'Mozambique');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (116, 'Myanmar');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (117, 'Namibia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (118, 'Nauru');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (119, 'Nepal');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (120, 'Netherlands');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (121, 'New Zealand');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (122, 'Nicaragua');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (123, 'Niger');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (124, 'Nigeria');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (125, 'North Korea');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (126, 'North Macedonia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (127, 'Norway');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (128, 'Oman');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (129, 'Pakistan');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (130, 'Palau');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (131, 'Panama');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (132, 'Papua New Guinea');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (133, 'Paraguay');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (134, 'Peru');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (135, 'Philippines');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (136, 'Poland');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (137, 'Portugal');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (138, 'Qatar');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (139, 'Romania');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (140, 'Russia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (141, 'Rwanda');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (142, 'Saint Kitts and Nevis');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (143, 'Saint Lucia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (144, 'Saint Vincent and the Grenadines');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (145, 'Samoa');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (146, 'San Marino');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (147, 'Sao Tome and Principe');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (148, 'Saudi Arabia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (149, 'Senegal');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (150, 'Serbia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (151, 'Seychelles');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (152, 'Sierra Leone');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (153, 'Singapore');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (154, 'Slovakia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (155, 'Slovenia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (156, 'Solomon Islands');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (157, 'Somalia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (158, 'South Africa');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (159, 'South Korea');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (160, 'South Sudan');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (161, 'Spain');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (162, 'Sri Lanka');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (163, 'Sudan');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (164, 'Suriname');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (165, 'Sweden');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (166, 'Switzerland');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (167, 'Syria');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (168, 'Taiwan');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (169, 'Tajikistan');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (170, 'Tanzania');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (171, 'Thailand');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (172, 'Timor-Leste');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (173, 'Togo');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (174, 'Tonga');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (175, 'Trinidad and Tobago');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (176, 'Tunisia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (177, 'Turkey');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (178, 'Turkmenistan');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (179, 'Tuvalu');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (180, 'Uganda');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (181, 'Ukraine');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (182, 'United Arab Emirates');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (183, 'United Kingdom');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (184, 'United States');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (185, 'Uruguay');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (186, 'Uzbekistan');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (187, 'Vanuatu');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (188, 'Vatican City');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (189, 'Venezuela');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (190, 'Vietnam');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (191, 'Yemen');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (192, 'Zambia');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (193, 'Zimbabwe');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (194, 'Kosovo');
INSERT INTO COUNTRY (Country_ID, Country_Name) VALUES (195, 'Palestine');