insert into CITY (City_ID, City_Name, Country_ID) values (1, 'Tallinn', 170);
insert into CITY (City_ID, City_Name, Country_ID) values (2, 'Fier', 158);
insert into CITY (City_ID, City_Name, Country_ID) values (3, 'Chapimarca', 470);
insert into CITY (City_ID, City_Name, Country_ID) values (4, 'Kiiminki', 152);
insert into CITY (City_ID, City_Name, Country_ID) values (5, 'Langgen', 48);
insert into CITY (City_ID, City_Name, Country_ID) values (6, 'Pulupandan', 169);
insert into CITY (City_ID, City_Name, Country_ID) values (7, 'Bardiyā', 399);
insert into CITY (City_ID, City_Name, Country_ID) values (8, 'Qianfoling', 410);
insert into CITY (City_ID, City_Name, Country_ID) values (9, 'Naekan', 425);
insert into CITY (City_ID, City_Name, Country_ID) values (10, 'Rakiv Lis', 412);
insert into CITY (City_ID, City_Name, Country_ID) values (11, 'Emiliano Zapata', 323);
insert into CITY (City_ID, City_Name, Country_ID) values (12, 'Onsala', 302);
insert into CITY (City_ID, City_Name, Country_ID) values (13, 'Paradise', 107);
insert into CITY (City_ID, City_Name, Country_ID) values (14, 'Fenggang', 48);
insert into CITY (City_ID, City_Name, Country_ID) values (15, 'Tekes', 304);
insert into CITY (City_ID, City_Name, Country_ID) values (16, 'Jiangbu', 252);
insert into CITY (City_ID, City_Name, Country_ID) values (17, 'Socorro', 349);
insert into CITY (City_ID, City_Name, Country_ID) values (18, 'Xingong', 239);
insert into CITY (City_ID, City_Name, Country_ID) values (19, 'Anserma', 224);
insert into CITY (City_ID, City_Name, Country_ID) values (20, 'Novoye Leushino', 271);
insert into CITY (City_ID, City_Name, Country_ID) values (21, 'Jacura', 140);
insert into CITY (City_ID, City_Name, Country_ID) values (22, 'Kowale', 108);
insert into CITY (City_ID, City_Name, Country_ID) values (23, 'Jardim', 24);
insert into CITY (City_ID, City_Name, Country_ID) values (24, 'Samothráki', 345);
insert into CITY (City_ID, City_Name, Country_ID) values (25, 'Banqiao', 155);
insert into CITY (City_ID, City_Name, Country_ID) values (26, 'Puyang', 499);
insert into CITY (City_ID, City_Name, Country_ID) values (27, 'Krasnyy Yar', 200);
insert into CITY (City_ID, City_Name, Country_ID) values (28, 'Huntington', 220);
insert into CITY (City_ID, City_Name, Country_ID) values (29, 'Siao', 427);
insert into CITY (City_ID, City_Name, Country_ID) values (30, 'Krzyżanów', 495);
insert into CITY (City_ID, City_Name, Country_ID) values (31, 'Katoro', 229);
insert into CITY (City_ID, City_Name, Country_ID) values (32, 'Al Ḩāmūl', 286);
insert into CITY (City_ID, City_Name, Country_ID) values (33, 'Itajuípe', 170);
insert into CITY (City_ID, City_Name, Country_ID) values (34, 'Pescara', 299);
insert into CITY (City_ID, City_Name, Country_ID) values (35, 'Tlučná', 219);
insert into CITY (City_ID, City_Name, Country_ID) values (36, 'Kolchikón', 327);
insert into CITY (City_ID, City_Name, Country_ID) values (37, 'Zaklików', 225);
insert into CITY (City_ID, City_Name, Country_ID) values (38, 'Nangerang', 111);
insert into CITY (City_ID, City_Name, Country_ID) values (39, 'Doāba', 182);
insert into CITY (City_ID, City_Name, Country_ID) values (40, 'Jagüey Grande', 116);
insert into CITY (City_ID, City_Name, Country_ID) values (41, 'Puerto Boyacá', 494);
insert into CITY (City_ID, City_Name, Country_ID) values (42, 'Tulyushka', 46);
insert into CITY (City_ID, City_Name, Country_ID) values (43, 'Monkayo', 387);
insert into CITY (City_ID, City_Name, Country_ID) values (44, 'Vladimir', 205);
insert into CITY (City_ID, City_Name, Country_ID) values (45, 'Cibeureum Satu', 79);
insert into CITY (City_ID, City_Name, Country_ID) values (46, 'Libacao', 450);
insert into CITY (City_ID, City_Name, Country_ID) values (47, 'Marsada', 5);
insert into CITY (City_ID, City_Name, Country_ID) values (48, 'Lianghu', 277);
insert into CITY (City_ID, City_Name, Country_ID) values (49, 'Paris 13', 33);
insert into CITY (City_ID, City_Name, Country_ID) values (50, 'Hecun', 267);
insert into CITY (City_ID, City_Name, Country_ID) values (51, 'Khal’ch', 244);
insert into CITY (City_ID, City_Name, Country_ID) values (52, 'Hongjia', 353);
insert into CITY (City_ID, City_Name, Country_ID) values (53, 'Campamento', 252);
insert into CITY (City_ID, City_Name, Country_ID) values (54, 'Thị Trấn Nguyên Bình', 120);
insert into CITY (City_ID, City_Name, Country_ID) values (55, 'Debrecen', 362);
insert into CITY (City_ID, City_Name, Country_ID) values (56, 'Viengxay', 393);
insert into CITY (City_ID, City_Name, Country_ID) values (57, 'Huyuan', 38);
insert into CITY (City_ID, City_Name, Country_ID) values (58, 'Suizhong', 230);
insert into CITY (City_ID, City_Name, Country_ID) values (59, 'Buôn Ma Thuột', 80);
insert into CITY (City_ID, City_Name, Country_ID) values (60, 'Thung Yang Daeng', 232);
insert into CITY (City_ID, City_Name, Country_ID) values (61, 'Saku', 203);
insert into CITY (City_ID, City_Name, Country_ID) values (62, 'Buyunshan', 119);
insert into CITY (City_ID, City_Name, Country_ID) values (63, 'Detroit', 152);
insert into CITY (City_ID, City_Name, Country_ID) values (64, 'Biaokou', 346);
insert into CITY (City_ID, City_Name, Country_ID) values (65, 'Prado', 291);
insert into CITY (City_ID, City_Name, Country_ID) values (66, 'Fuxi', 9);
insert into CITY (City_ID, City_Name, Country_ID) values (67, 'Slobodskoy', 447);
insert into CITY (City_ID, City_Name, Country_ID) values (68, 'Ấp Tân Ngãi', 206);
insert into CITY (City_ID, City_Name, Country_ID) values (69, 'Oematnunu', 386);
insert into CITY (City_ID, City_Name, Country_ID) values (70, 'Meilin', 74);
insert into CITY (City_ID, City_Name, Country_ID) values (71, 'Daxi', 94);
insert into CITY (City_ID, City_Name, Country_ID) values (72, 'Haukivuori', 166);
insert into CITY (City_ID, City_Name, Country_ID) values (73, 'Viga', 360);
insert into CITY (City_ID, City_Name, Country_ID) values (74, 'Bafoussam', 267);
insert into CITY (City_ID, City_Name, Country_ID) values (75, 'Ban Nahin', 271);
insert into CITY (City_ID, City_Name, Country_ID) values (76, 'Stavyshche', 193);
insert into CITY (City_ID, City_Name, Country_ID) values (77, 'Khatsyezhyna', 451);
insert into CITY (City_ID, City_Name, Country_ID) values (78, 'Ciechocin', 355);
insert into CITY (City_ID, City_Name, Country_ID) values (79, 'Mercedes', 10);
insert into CITY (City_ID, City_Name, Country_ID) values (80, 'Quisqueya', 432);
insert into CITY (City_ID, City_Name, Country_ID) values (81, 'Notranje Gorice', 226);
insert into CITY (City_ID, City_Name, Country_ID) values (82, 'Jiangnan', 277);
insert into CITY (City_ID, City_Name, Country_ID) values (83, 'Krivodanovka', 495);
insert into CITY (City_ID, City_Name, Country_ID) values (84, 'Jixin', 334);
insert into CITY (City_ID, City_Name, Country_ID) values (85, 'Laborde', 259);
insert into CITY (City_ID, City_Name, Country_ID) values (86, 'Bāgh-e Maīdān', 223);
insert into CITY (City_ID, City_Name, Country_ID) values (87, 'El Alamo', 500);
insert into CITY (City_ID, City_Name, Country_ID) values (88, 'Mat-i', 471);
insert into CITY (City_ID, City_Name, Country_ID) values (89, 'Changfu', 379);
insert into CITY (City_ID, City_Name, Country_ID) values (90, 'Madalena', 399);
insert into CITY (City_ID, City_Name, Country_ID) values (91, 'Nador', 129);
insert into CITY (City_ID, City_Name, Country_ID) values (92, 'Córdoba', 339);
insert into CITY (City_ID, City_Name, Country_ID) values (93, 'Furukawa', 96);
insert into CITY (City_ID, City_Name, Country_ID) values (94, 'Pupiales', 361);
insert into CITY (City_ID, City_Name, Country_ID) values (95, 'Liaobu', 403);
insert into CITY (City_ID, City_Name, Country_ID) values (96, 'Paprotnia', 417);
insert into CITY (City_ID, City_Name, Country_ID) values (97, 'Villa Altagracia', 102);
insert into CITY (City_ID, City_Name, Country_ID) values (98, 'Bataiporã', 98);
insert into CITY (City_ID, City_Name, Country_ID) values (99, 'Huilongshan', 142);
insert into CITY (City_ID, City_Name, Country_ID) values (100, 'Tongtuan', 436);
insert into CITY (City_ID, City_Name, Country_ID) values (101, 'Harderwijk', 274);
insert into CITY (City_ID, City_Name, Country_ID) values (102, 'Paris 15', 12);
insert into CITY (City_ID, City_Name, Country_ID) values (103, 'San Jacinto', 308);
insert into CITY (City_ID, City_Name, Country_ID) values (104, 'Hamburg', 120);
insert into CITY (City_ID, City_Name, Country_ID) values (105, 'Khatsyezhyna', 327);
insert into CITY (City_ID, City_Name, Country_ID) values (106, 'Ōgaki', 312);
insert into CITY (City_ID, City_Name, Country_ID) values (107, 'Ruteng', 242);
insert into CITY (City_ID, City_Name, Country_ID) values (108, 'Socorro', 16);
insert into CITY (City_ID, City_Name, Country_ID) values (109, 'Gaojiabu', 198);
insert into CITY (City_ID, City_Name, Country_ID) values (110, 'Pardelhas', 299);
insert into CITY (City_ID, City_Name, Country_ID) values (111, 'Zruč nad Sázavou', 74);
insert into CITY (City_ID, City_Name, Country_ID) values (112, 'Melaka', 224);
insert into CITY (City_ID, City_Name, Country_ID) values (113, 'Ashgabat', 175);
insert into CITY (City_ID, City_Name, Country_ID) values (114, 'Tefé', 12);
insert into CITY (City_ID, City_Name, Country_ID) values (115, 'Xingdian', 392);
insert into CITY (City_ID, City_Name, Country_ID) values (116, 'Caibarién', 325);
insert into CITY (City_ID, City_Name, Country_ID) values (117, 'Uglich', 136);
insert into CITY (City_ID, City_Name, Country_ID) values (118, 'Dresden', 291);
insert into CITY (City_ID, City_Name, Country_ID) values (119, 'Hepingyizu', 93);
insert into CITY (City_ID, City_Name, Country_ID) values (120, 'Thabazimbi', 59);
insert into CITY (City_ID, City_Name, Country_ID) values (121, 'Pindushi', 149);
insert into CITY (City_ID, City_Name, Country_ID) values (122, 'Thulamahashi', 301);
insert into CITY (City_ID, City_Name, Country_ID) values (123, 'Blerim', 417);
insert into CITY (City_ID, City_Name, Country_ID) values (124, 'Soloma', 10);
insert into CITY (City_ID, City_Name, Country_ID) values (125, 'Yeniugou', 5);
insert into CITY (City_ID, City_Name, Country_ID) values (126, 'Juzhen', 46);
insert into CITY (City_ID, City_Name, Country_ID) values (127, 'Rokiciny', 356);
insert into CITY (City_ID, City_Name, Country_ID) values (128, 'Yangshan', 487);
insert into CITY (City_ID, City_Name, Country_ID) values (129, 'Al Wardānīn', 65);
insert into CITY (City_ID, City_Name, Country_ID) values (130, 'Sausa', 337);
insert into CITY (City_ID, City_Name, Country_ID) values (131, 'Energeticheskiy', 284);
insert into CITY (City_ID, City_Name, Country_ID) values (132, 'Sariwŏn', 64);
insert into CITY (City_ID, City_Name, Country_ID) values (133, 'Chornyanka', 312);
insert into CITY (City_ID, City_Name, Country_ID) values (134, 'Áno Kopanákion', 108);
insert into CITY (City_ID, City_Name, Country_ID) values (135, 'Najd al Jumā‘ī', 242);
insert into CITY (City_ID, City_Name, Country_ID) values (136, 'Banyue', 95);
insert into CITY (City_ID, City_Name, Country_ID) values (137, 'Mundolsheim', 431);
insert into CITY (City_ID, City_Name, Country_ID) values (138, 'Sobreira', 159);
insert into CITY (City_ID, City_Name, Country_ID) values (139, 'Jinxiang', 302);
insert into CITY (City_ID, City_Name, Country_ID) values (140, 'Vónitsa', 158);
insert into CITY (City_ID, City_Name, Country_ID) values (141, 'Tchintabaraden', 467);
insert into CITY (City_ID, City_Name, Country_ID) values (142, 'Dolní Dunajovice', 103);
insert into CITY (City_ID, City_Name, Country_ID) values (143, 'Ponta do Sol', 70);
insert into CITY (City_ID, City_Name, Country_ID) values (144, 'Amadora', 114);
insert into CITY (City_ID, City_Name, Country_ID) values (145, 'Włosienica', 250);
insert into CITY (City_ID, City_Name, Country_ID) values (146, 'Makato', 11);
insert into CITY (City_ID, City_Name, Country_ID) values (147, 'Beishan', 461);
insert into CITY (City_ID, City_Name, Country_ID) values (148, 'Beberibe', 294);
insert into CITY (City_ID, City_Name, Country_ID) values (149, 'Huntington', 92);
insert into CITY (City_ID, City_Name, Country_ID) values (150, 'Even Yehuda', 111);
insert into CITY (City_ID, City_Name, Country_ID) values (151, 'Santo António da Charneca', 268);
insert into CITY (City_ID, City_Name, Country_ID) values (152, 'Kiritsy', 186);
insert into CITY (City_ID, City_Name, Country_ID) values (153, 'Paris 09', 291);
insert into CITY (City_ID, City_Name, Country_ID) values (154, 'Akkol’', 373);
insert into CITY (City_ID, City_Name, Country_ID) values (155, 'Qiancang', 48);
insert into CITY (City_ID, City_Name, Country_ID) values (156, 'Phu Kam Yao', 125);
insert into CITY (City_ID, City_Name, Country_ID) values (157, 'Libon', 41);
insert into CITY (City_ID, City_Name, Country_ID) values (158, 'Furmanov', 252);
insert into CITY (City_ID, City_Name, Country_ID) values (159, 'Dijon', 299);
insert into CITY (City_ID, City_Name, Country_ID) values (160, 'Kalýves Polygýrou', 218);
insert into CITY (City_ID, City_Name, Country_ID) values (161, 'Cunliji', 395);
insert into CITY (City_ID, City_Name, Country_ID) values (162, 'Kedawung', 437);
insert into CITY (City_ID, City_Name, Country_ID) values (163, 'Lop', 204);
insert into CITY (City_ID, City_Name, Country_ID) values (164, 'Uzhhorod', 437);
insert into CITY (City_ID, City_Name, Country_ID) values (165, 'Catabola', 451);
insert into CITY (City_ID, City_Name, Country_ID) values (166, 'Bulalacao', 79);
insert into CITY (City_ID, City_Name, Country_ID) values (167, 'Timpas', 400);
insert into CITY (City_ID, City_Name, Country_ID) values (168, 'La Carlota', 16);
insert into CITY (City_ID, City_Name, Country_ID) values (169, 'Libato', 320);
insert into CITY (City_ID, City_Name, Country_ID) values (170, 'Hongqiao', 96);
insert into CITY (City_ID, City_Name, Country_ID) values (171, 'Omsk', 249);
insert into CITY (City_ID, City_Name, Country_ID) values (172, 'Atlanta', 411);
insert into CITY (City_ID, City_Name, Country_ID) values (173, 'Zlatni Pyasatsi', 234);
insert into CITY (City_ID, City_Name, Country_ID) values (174, 'Voznesenskaya', 84);
insert into CITY (City_ID, City_Name, Country_ID) values (175, 'Padangulaktanding', 47);
insert into CITY (City_ID, City_Name, Country_ID) values (176, 'Andros Town', 98);
insert into CITY (City_ID, City_Name, Country_ID) values (177, 'Comalapa', 251);
insert into CITY (City_ID, City_Name, Country_ID) values (178, 'Apaga', 12);
insert into CITY (City_ID, City_Name, Country_ID) values (179, 'Quimistán', 497);
insert into CITY (City_ID, City_Name, Country_ID) values (180, 'Jagabaya Dua', 476);
insert into CITY (City_ID, City_Name, Country_ID) values (181, 'Sampacho', 138);
insert into CITY (City_ID, City_Name, Country_ID) values (182, 'Khāngāh Dogrān', 125);
insert into CITY (City_ID, City_Name, Country_ID) values (183, 'Xiangba', 32);
insert into CITY (City_ID, City_Name, Country_ID) values (184, 'Oygon', 340);
insert into CITY (City_ID, City_Name, Country_ID) values (185, 'Sucre', 399);
insert into CITY (City_ID, City_Name, Country_ID) values (186, 'Centar Župa', 491);
insert into CITY (City_ID, City_Name, Country_ID) values (187, 'San Pedro', 182);
insert into CITY (City_ID, City_Name, Country_ID) values (188, 'Hebeitun', 271);
insert into CITY (City_ID, City_Name, Country_ID) values (189, 'Florence', 480);
insert into CITY (City_ID, City_Name, Country_ID) values (190, 'Jinshan', 232);
insert into CITY (City_ID, City_Name, Country_ID) values (191, 'Jiaokui', 196);
insert into CITY (City_ID, City_Name, Country_ID) values (192, 'Sobreira', 150);
insert into CITY (City_ID, City_Name, Country_ID) values (193, 'Roma', 382);
insert into CITY (City_ID, City_Name, Country_ID) values (194, 'Orléans', 290);
insert into CITY (City_ID, City_Name, Country_ID) values (195, 'Chugay', 9);
insert into CITY (City_ID, City_Name, Country_ID) values (196, 'Zhantang', 304);
insert into CITY (City_ID, City_Name, Country_ID) values (197, 'Olutanga', 487);
insert into CITY (City_ID, City_Name, Country_ID) values (198, 'Wujingfu', 377);
insert into CITY (City_ID, City_Name, Country_ID) values (199, 'Camilaca', 12);
insert into CITY (City_ID, City_Name, Country_ID) values (200, 'Domsjö', 238);
insert into CITY (City_ID, City_Name, Country_ID) values (201, 'Santa Elena', 453);
insert into CITY (City_ID, City_Name, Country_ID) values (202, 'Zhaixi', 294);
insert into CITY (City_ID, City_Name, Country_ID) values (203, 'Yenagoa', 146);
insert into CITY (City_ID, City_Name, Country_ID) values (204, 'Konārak', 153);
insert into CITY (City_ID, City_Name, Country_ID) values (205, 'Imsida', 316);
insert into CITY (City_ID, City_Name, Country_ID) values (206, 'Macroom', 391);
insert into CITY (City_ID, City_Name, Country_ID) values (207, 'Itatuba', 488);
insert into CITY (City_ID, City_Name, Country_ID) values (208, 'Roanoke', 349);
insert into CITY (City_ID, City_Name, Country_ID) values (209, 'Chayek', 403);
insert into CITY (City_ID, City_Name, Country_ID) values (210, 'Candijay', 145);
insert into CITY (City_ID, City_Name, Country_ID) values (211, 'Patos Fshat', 156);
insert into CITY (City_ID, City_Name, Country_ID) values (212, 'Puji', 13);
insert into CITY (City_ID, City_Name, Country_ID) values (213, 'Cilegi', 102);
insert into CITY (City_ID, City_Name, Country_ID) values (214, 'Leuwidamar', 478);
insert into CITY (City_ID, City_Name, Country_ID) values (215, 'Ma’ao', 337);
insert into CITY (City_ID, City_Name, Country_ID) values (216, 'Poli', 302);
insert into CITY (City_ID, City_Name, Country_ID) values (217, 'Yala', 284);
insert into CITY (City_ID, City_Name, Country_ID) values (218, 'Changqiao', 483);
insert into CITY (City_ID, City_Name, Country_ID) values (219, 'Nekrasovka', 104);
insert into CITY (City_ID, City_Name, Country_ID) values (220, 'Uralets', 22);
insert into CITY (City_ID, City_Name, Country_ID) values (221, 'Uruguaiana', 427);
insert into CITY (City_ID, City_Name, Country_ID) values (222, 'Amgalang', 214);
insert into CITY (City_ID, City_Name, Country_ID) values (223, 'Banshu', 477);
insert into CITY (City_ID, City_Name, Country_ID) values (224, 'Lewo', 393);
insert into CITY (City_ID, City_Name, Country_ID) values (225, 'Hanggan', 239);
insert into CITY (City_ID, City_Name, Country_ID) values (226, 'Saint-Raymond', 101);
insert into CITY (City_ID, City_Name, Country_ID) values (227, 'Sukhobezvodnoye', 237);
insert into CITY (City_ID, City_Name, Country_ID) values (228, 'Herong', 267);
insert into CITY (City_ID, City_Name, Country_ID) values (229, 'Amieira', 223);
insert into CITY (City_ID, City_Name, Country_ID) values (230, 'Ypacarai', 480);
insert into CITY (City_ID, City_Name, Country_ID) values (231, 'Anren', 235);
insert into CITY (City_ID, City_Name, Country_ID) values (232, 'Tocota', 475);
insert into CITY (City_ID, City_Name, Country_ID) values (233, 'Valence', 482);
insert into CITY (City_ID, City_Name, Country_ID) values (234, 'Amarillo', 141);
insert into CITY (City_ID, City_Name, Country_ID) values (235, 'Bungtiang Barat', 395);
insert into CITY (City_ID, City_Name, Country_ID) values (236, 'Bender', 350);
insert into CITY (City_ID, City_Name, Country_ID) values (237, 'Pindi Gheb', 488);
insert into CITY (City_ID, City_Name, Country_ID) values (238, 'Xincheng', 129);
insert into CITY (City_ID, City_Name, Country_ID) values (239, 'Valdivia', 257);
insert into CITY (City_ID, City_Name, Country_ID) values (240, 'Denver', 295);
insert into CITY (City_ID, City_Name, Country_ID) values (241, 'Manukau City', 18);
insert into CITY (City_ID, City_Name, Country_ID) values (242, 'Al Fūlah', 162);
insert into CITY (City_ID, City_Name, Country_ID) values (243, 'Abrantes', 106);
insert into CITY (City_ID, City_Name, Country_ID) values (244, 'Daduo', 11);
insert into CITY (City_ID, City_Name, Country_ID) values (245, 'Daminggong', 289);
insert into CITY (City_ID, City_Name, Country_ID) values (246, 'Descalvado', 484);
insert into CITY (City_ID, City_Name, Country_ID) values (247, 'Ajung', 171);
insert into CITY (City_ID, City_Name, Country_ID) values (248, 'Mindupok', 232);
insert into CITY (City_ID, City_Name, Country_ID) values (249, 'Yantian', 445);
insert into CITY (City_ID, City_Name, Country_ID) values (250, 'Klimontów', 126);
insert into CITY (City_ID, City_Name, Country_ID) values (251, 'Krzanowice', 124);
insert into CITY (City_ID, City_Name, Country_ID) values (252, 'Meshcherino', 38);
insert into CITY (City_ID, City_Name, Country_ID) values (253, 'Yushan', 379);
insert into CITY (City_ID, City_Name, Country_ID) values (254, 'Теарце', 143);
insert into CITY (City_ID, City_Name, Country_ID) values (255, 'Wysoka', 428);
insert into CITY (City_ID, City_Name, Country_ID) values (256, 'Linzi', 66);
insert into CITY (City_ID, City_Name, Country_ID) values (257, 'Pak Phanang', 348);
insert into CITY (City_ID, City_Name, Country_ID) values (258, 'Lamalera', 482);
insert into CITY (City_ID, City_Name, Country_ID) values (259, 'Miliangju', 319);
insert into CITY (City_ID, City_Name, Country_ID) values (260, 'Anbyŏn-ŭp', 376);
insert into CITY (City_ID, City_Name, Country_ID) values (261, 'Fanzeres', 49);
insert into CITY (City_ID, City_Name, Country_ID) values (262, 'Krajan', 448);
insert into CITY (City_ID, City_Name, Country_ID) values (263, 'Pernå', 146);
insert into CITY (City_ID, City_Name, Country_ID) values (264, 'Tayum', 226);
insert into CITY (City_ID, City_Name, Country_ID) values (265, 'Khelyulya', 178);
insert into CITY (City_ID, City_Name, Country_ID) values (266, 'Tsuma', 171);
insert into CITY (City_ID, City_Name, Country_ID) values (267, 'Gunjur Kuta', 316);
insert into CITY (City_ID, City_Name, Country_ID) values (268, 'Cuyotenango', 292);
insert into CITY (City_ID, City_Name, Country_ID) values (269, 'Néos Skopós', 486);
insert into CITY (City_ID, City_Name, Country_ID) values (270, 'Huicheng', 271);
insert into CITY (City_ID, City_Name, Country_ID) values (271, 'Cipanas', 416);
insert into CITY (City_ID, City_Name, Country_ID) values (272, 'Haodian', 493);
insert into CITY (City_ID, City_Name, Country_ID) values (273, 'Waiholo', 193);
insert into CITY (City_ID, City_Name, Country_ID) values (274, 'Zhouzai', 310);
insert into CITY (City_ID, City_Name, Country_ID) values (275, 'Balahovit', 243);
insert into CITY (City_ID, City_Name, Country_ID) values (276, 'Dampit', 430);
insert into CITY (City_ID, City_Name, Country_ID) values (277, 'Yuezhao', 192);
insert into CITY (City_ID, City_Name, Country_ID) values (278, 'As Suqaylibīyah', 292);
insert into CITY (City_ID, City_Name, Country_ID) values (279, 'Carregado', 232);
insert into CITY (City_ID, City_Name, Country_ID) values (280, 'Złotów', 295);
insert into CITY (City_ID, City_Name, Country_ID) values (281, 'Dandai', 430);
insert into CITY (City_ID, City_Name, Country_ID) values (282, 'San Antonio', 202);
insert into CITY (City_ID, City_Name, Country_ID) values (283, 'Brunssum', 269);
insert into CITY (City_ID, City_Name, Country_ID) values (284, 'Chřibská', 265);
insert into CITY (City_ID, City_Name, Country_ID) values (285, 'Seda', 121);
insert into CITY (City_ID, City_Name, Country_ID) values (286, 'Astypálaia', 154);
insert into CITY (City_ID, City_Name, Country_ID) values (287, 'Ulashan', 460);
insert into CITY (City_ID, City_Name, Country_ID) values (288, 'Hampton', 330);
insert into CITY (City_ID, City_Name, Country_ID) values (289, 'Huadi', 469);
insert into CITY (City_ID, City_Name, Country_ID) values (290, 'Sokyryany', 482);
insert into CITY (City_ID, City_Name, Country_ID) values (291, 'Gasri', 335);
insert into CITY (City_ID, City_Name, Country_ID) values (292, 'Bukonyo', 437);
insert into CITY (City_ID, City_Name, Country_ID) values (293, 'Şurmān', 388);
insert into CITY (City_ID, City_Name, Country_ID) values (294, 'Águas Vermelhas', 342);
insert into CITY (City_ID, City_Name, Country_ID) values (295, 'Yŏnmu', 420);
insert into CITY (City_ID, City_Name, Country_ID) values (296, 'Sukodono', 422);
insert into CITY (City_ID, City_Name, Country_ID) values (297, 'København', 240);
insert into CITY (City_ID, City_Name, Country_ID) values (298, 'Mashui', 212);
insert into CITY (City_ID, City_Name, Country_ID) values (299, 'Tegalgunung', 14);
insert into CITY (City_ID, City_Name, Country_ID) values (300, 'Bangko', 133);
insert into CITY (City_ID, City_Name, Country_ID) values (301, 'Lashma', 429);
insert into CITY (City_ID, City_Name, Country_ID) values (302, 'Velká Dobrá', 454);
insert into CITY (City_ID, City_Name, Country_ID) values (303, 'Toupopu', 441);
insert into CITY (City_ID, City_Name, Country_ID) values (304, 'Zoumi', 267);
insert into CITY (City_ID, City_Name, Country_ID) values (305, 'Matina', 294);
insert into CITY (City_ID, City_Name, Country_ID) values (306, 'Sedatigede', 324);
insert into CITY (City_ID, City_Name, Country_ID) values (307, 'Älmhult', 6);
insert into CITY (City_ID, City_Name, Country_ID) values (308, 'San Francisco', 247);
insert into CITY (City_ID, City_Name, Country_ID) values (309, 'Campo Largo', 152);
insert into CITY (City_ID, City_Name, Country_ID) values (310, 'Anqing', 203);
insert into CITY (City_ID, City_Name, Country_ID) values (311, 'Iizuka', 414);
insert into CITY (City_ID, City_Name, Country_ID) values (312, 'Banyutengah', 236);
insert into CITY (City_ID, City_Name, Country_ID) values (313, 'Hantsavichy', 171);
insert into CITY (City_ID, City_Name, Country_ID) values (314, 'Luntai', 368);
insert into CITY (City_ID, City_Name, Country_ID) values (315, 'Gaoyi', 398);
insert into CITY (City_ID, City_Name, Country_ID) values (316, 'Callahuanca', 241);
insert into CITY (City_ID, City_Name, Country_ID) values (317, 'Majunying', 208);
insert into CITY (City_ID, City_Name, Country_ID) values (318, 'Bukuru', 82);
insert into CITY (City_ID, City_Name, Country_ID) values (319, 'Jiuxian', 167);
insert into CITY (City_ID, City_Name, Country_ID) values (320, 'Gose', 463);
insert into CITY (City_ID, City_Name, Country_ID) values (321, 'Yingmaili', 116);
insert into CITY (City_ID, City_Name, Country_ID) values (322, 'Lennec', 26);
insert into CITY (City_ID, City_Name, Country_ID) values (323, 'Tutayev', 427);
insert into CITY (City_ID, City_Name, Country_ID) values (324, 'Konga', 299);
insert into CITY (City_ID, City_Name, Country_ID) values (325, 'Micheng', 263);
insert into CITY (City_ID, City_Name, Country_ID) values (326, 'Xarsingma', 73);
insert into CITY (City_ID, City_Name, Country_ID) values (327, 'Yangdu', 439);
insert into CITY (City_ID, City_Name, Country_ID) values (328, 'Xidajie', 197);
insert into CITY (City_ID, City_Name, Country_ID) values (329, 'Xingang', 290);
insert into CITY (City_ID, City_Name, Country_ID) values (330, 'Derzhavīnsk', 7);
insert into CITY (City_ID, City_Name, Country_ID) values (331, 'Qaffīn', 313);
insert into CITY (City_ID, City_Name, Country_ID) values (332, 'Pexiligais', 226);
insert into CITY (City_ID, City_Name, Country_ID) values (333, 'Dairiti', 26);
insert into CITY (City_ID, City_Name, Country_ID) values (334, 'Āsasa', 49);
insert into CITY (City_ID, City_Name, Country_ID) values (335, 'Leuwayang', 380);
insert into CITY (City_ID, City_Name, Country_ID) values (336, 'Ińsko', 138);
insert into CITY (City_ID, City_Name, Country_ID) values (337, 'Kisela Voda', 296);
insert into CITY (City_ID, City_Name, Country_ID) values (338, 'Bobrov', 409);
insert into CITY (City_ID, City_Name, Country_ID) values (339, 'Kawęczyn', 319);
insert into CITY (City_ID, City_Name, Country_ID) values (340, 'Bojongsarung', 62);
insert into CITY (City_ID, City_Name, Country_ID) values (341, 'Alcaria', 289);
insert into CITY (City_ID, City_Name, Country_ID) values (342, 'Troyan', 120);
insert into CITY (City_ID, City_Name, Country_ID) values (343, 'Marcala', 251);
insert into CITY (City_ID, City_Name, Country_ID) values (344, 'Primošten', 38);
insert into CITY (City_ID, City_Name, Country_ID) values (345, 'Skien', 3);
insert into CITY (City_ID, City_Name, Country_ID) values (346, 'Togu', 237);
insert into CITY (City_ID, City_Name, Country_ID) values (347, 'Ipoh', 212);
insert into CITY (City_ID, City_Name, Country_ID) values (348, 'Armavir', 387);
insert into CITY (City_ID, City_Name, Country_ID) values (349, 'Méru', 31);
insert into CITY (City_ID, City_Name, Country_ID) values (350, 'Gllogjan', 263);
insert into CITY (City_ID, City_Name, Country_ID) values (351, 'Gorno Orizari', 26);
insert into CITY (City_ID, City_Name, Country_ID) values (352, 'Ludvika', 147);
insert into CITY (City_ID, City_Name, Country_ID) values (353, 'Serednye', 192);
insert into CITY (City_ID, City_Name, Country_ID) values (354, 'Mogapi', 30);
insert into CITY (City_ID, City_Name, Country_ID) values (355, 'Tonj', 40);
insert into CITY (City_ID, City_Name, Country_ID) values (356, 'Bolinao', 153);
insert into CITY (City_ID, City_Name, Country_ID) values (357, 'Kaputian', 365);
insert into CITY (City_ID, City_Name, Country_ID) values (358, 'Yuezhao', 218);
insert into CITY (City_ID, City_Name, Country_ID) values (359, 'Bribir', 221);
insert into CITY (City_ID, City_Name, Country_ID) values (360, 'Tenri', 233);
insert into CITY (City_ID, City_Name, Country_ID) values (361, 'Jinqiao', 288);
insert into CITY (City_ID, City_Name, Country_ID) values (362, 'Pubu', 247);
insert into CITY (City_ID, City_Name, Country_ID) values (363, 'Juan N Alvarez', 397);
insert into CITY (City_ID, City_Name, Country_ID) values (364, 'Koygorodok', 375);
insert into CITY (City_ID, City_Name, Country_ID) values (365, 'El Zapote', 483);
insert into CITY (City_ID, City_Name, Country_ID) values (366, 'Mitrópoli', 221);
insert into CITY (City_ID, City_Name, Country_ID) values (367, 'Yucun', 19);
insert into CITY (City_ID, City_Name, Country_ID) values (368, 'Maisons-Laffitte', 480);
insert into CITY (City_ID, City_Name, Country_ID) values (369, 'Telengsari', 38);
insert into CITY (City_ID, City_Name, Country_ID) values (370, 'Niandui', 198);
insert into CITY (City_ID, City_Name, Country_ID) values (371, 'Tingloy', 450);
insert into CITY (City_ID, City_Name, Country_ID) values (372, 'Xinmin', 362);
insert into CITY (City_ID, City_Name, Country_ID) values (373, 'Omaha', 191);
insert into CITY (City_ID, City_Name, Country_ID) values (374, 'Bureng', 92);
insert into CITY (City_ID, City_Name, Country_ID) values (375, 'Dārayyā', 138);
insert into CITY (City_ID, City_Name, Country_ID) values (376, 'Dasanlian Lauk', 120);
insert into CITY (City_ID, City_Name, Country_ID) values (377, 'La Reforma', 39);
insert into CITY (City_ID, City_Name, Country_ID) values (378, 'Baiguo', 185);
insert into CITY (City_ID, City_Name, Country_ID) values (379, 'Iwaki', 377);
insert into CITY (City_ID, City_Name, Country_ID) values (380, 'Araras', 391);
insert into CITY (City_ID, City_Name, Country_ID) values (381, 'Wanareja', 19);
insert into CITY (City_ID, City_Name, Country_ID) values (382, 'Kuala Tuha', 495);
insert into CITY (City_ID, City_Name, Country_ID) values (383, 'Kota Kinabalu', 63);
insert into CITY (City_ID, City_Name, Country_ID) values (384, 'Duszniki-Zdrój', 185);
insert into CITY (City_ID, City_Name, Country_ID) values (385, 'Cabra Figa', 348);
insert into CITY (City_ID, City_Name, Country_ID) values (386, 'Chornoliztsi', 424);
insert into CITY (City_ID, City_Name, Country_ID) values (387, 'Outeiro', 440);
insert into CITY (City_ID, City_Name, Country_ID) values (388, 'Longmen', 230);
insert into CITY (City_ID, City_Name, Country_ID) values (389, 'Vysoké nad Jizerou', 418);
insert into CITY (City_ID, City_Name, Country_ID) values (390, 'Rada Tilly', 476);
insert into CITY (City_ID, City_Name, Country_ID) values (391, 'Shuangxiqiao', 331);
insert into CITY (City_ID, City_Name, Country_ID) values (392, 'El Zulia', 292);
insert into CITY (City_ID, City_Name, Country_ID) values (393, 'Fajã de Cima', 452);
insert into CITY (City_ID, City_Name, Country_ID) values (394, 'Avignon', 120);
insert into CITY (City_ID, City_Name, Country_ID) values (395, 'Bantacan', 352);
insert into CITY (City_ID, City_Name, Country_ID) values (396, 'Hammam Sousse', 70);
insert into CITY (City_ID, City_Name, Country_ID) values (397, 'Dodol', 51);
insert into CITY (City_ID, City_Name, Country_ID) values (398, 'Singkup', 69);
insert into CITY (City_ID, City_Name, Country_ID) values (399, 'Rio Grande', 391);
insert into CITY (City_ID, City_Name, Country_ID) values (400, 'Shuntian', 345);
insert into CITY (City_ID, City_Name, Country_ID) values (401, 'Oullins', 468);
insert into CITY (City_ID, City_Name, Country_ID) values (402, 'Suvorovskaya', 370);
insert into CITY (City_ID, City_Name, Country_ID) values (403, 'Santa Cruz De Tenerife', 291);
insert into CITY (City_ID, City_Name, Country_ID) values (404, 'Forshaga', 122);
insert into CITY (City_ID, City_Name, Country_ID) values (405, 'Qiankou', 36);
insert into CITY (City_ID, City_Name, Country_ID) values (406, 'Santa Marta de Penaguião', 26);
insert into CITY (City_ID, City_Name, Country_ID) values (407, 'Szczawnica', 252);
insert into CITY (City_ID, City_Name, Country_ID) values (408, 'Xiyuan', 193);
insert into CITY (City_ID, City_Name, Country_ID) values (409, 'Krzynowłoga Mała', 347);
insert into CITY (City_ID, City_Name, Country_ID) values (410, 'Huallanca', 133);
insert into CITY (City_ID, City_Name, Country_ID) values (411, 'Wuying', 151);
insert into CITY (City_ID, City_Name, Country_ID) values (412, 'Shuanglongchang', 418);
insert into CITY (City_ID, City_Name, Country_ID) values (413, 'Lazaro Cardenas', 377);
insert into CITY (City_ID, City_Name, Country_ID) values (414, 'Luozhou', 390);
insert into CITY (City_ID, City_Name, Country_ID) values (415, 'Jiujianfang', 20);
insert into CITY (City_ID, City_Name, Country_ID) values (416, 'Watuka', 211);
insert into CITY (City_ID, City_Name, Country_ID) values (417, 'La Libertad', 476);
insert into CITY (City_ID, City_Name, Country_ID) values (418, 'Futian', 254);
insert into CITY (City_ID, City_Name, Country_ID) values (419, 'Hedong', 21);
insert into CITY (City_ID, City_Name, Country_ID) values (420, 'Fonseca', 10);
insert into CITY (City_ID, City_Name, Country_ID) values (421, 'Brändö', 435);
insert into CITY (City_ID, City_Name, Country_ID) values (422, 'Mikumi', 281);
insert into CITY (City_ID, City_Name, Country_ID) values (423, 'Seongnam-si', 62);
insert into CITY (City_ID, City_Name, Country_ID) values (424, 'Huage', 65);
insert into CITY (City_ID, City_Name, Country_ID) values (425, 'Dunkerque', 332);
insert into CITY (City_ID, City_Name, Country_ID) values (426, 'Xiangcheng', 260);
insert into CITY (City_ID, City_Name, Country_ID) values (427, 'Chengguan', 356);
insert into CITY (City_ID, City_Name, Country_ID) values (428, 'Mīāndoāb', 365);
insert into CITY (City_ID, City_Name, Country_ID) values (429, 'Arnelas', 483);
insert into CITY (City_ID, City_Name, Country_ID) values (430, 'Yoshkar-Ola', 435);
insert into CITY (City_ID, City_Name, Country_ID) values (431, 'Binitayan', 233);
insert into CITY (City_ID, City_Name, Country_ID) values (432, 'Gordeyevka', 163);
insert into CITY (City_ID, City_Name, Country_ID) values (433, 'La Rochelle', 101);
insert into CITY (City_ID, City_Name, Country_ID) values (434, 'Kuala Lumpur', 170);
insert into CITY (City_ID, City_Name, Country_ID) values (435, 'Pajarillo', 39);
insert into CITY (City_ID, City_Name, Country_ID) values (436, 'Hudson Bay', 61);
insert into CITY (City_ID, City_Name, Country_ID) values (437, 'Kasreman Wetan', 377);
insert into CITY (City_ID, City_Name, Country_ID) values (438, 'Cihaur', 139);
insert into CITY (City_ID, City_Name, Country_ID) values (439, 'Jilma', 473);
insert into CITY (City_ID, City_Name, Country_ID) values (440, 'Cayenne', 319);
insert into CITY (City_ID, City_Name, Country_ID) values (441, 'Alingsås', 383);
insert into CITY (City_ID, City_Name, Country_ID) values (442, 'Dessalines', 242);
insert into CITY (City_ID, City_Name, Country_ID) values (443, 'Bagikkedok Lauk', 381);
insert into CITY (City_ID, City_Name, Country_ID) values (444, 'Poxin', 122);
insert into CITY (City_ID, City_Name, Country_ID) values (445, 'Santiago', 258);
insert into CITY (City_ID, City_Name, Country_ID) values (446, 'Druju', 173);
insert into CITY (City_ID, City_Name, Country_ID) values (447, 'Ar Rābiyah', 122);
insert into CITY (City_ID, City_Name, Country_ID) values (448, 'Wanfang', 284);
insert into CITY (City_ID, City_Name, Country_ID) values (449, 'Xingou', 431);
insert into CITY (City_ID, City_Name, Country_ID) values (450, 'Caobi', 295);
insert into CITY (City_ID, City_Name, Country_ID) values (451, 'Huaitu', 431);
insert into CITY (City_ID, City_Name, Country_ID) values (452, 'Gračanica', 479);
insert into CITY (City_ID, City_Name, Country_ID) values (453, 'Ilioúpoli', 23);
insert into CITY (City_ID, City_Name, Country_ID) values (454, 'Sukamulya', 175);
insert into CITY (City_ID, City_Name, Country_ID) values (455, 'Sinjār', 315);
insert into CITY (City_ID, City_Name, Country_ID) values (456, 'Pazarić', 146);
insert into CITY (City_ID, City_Name, Country_ID) values (457, 'Bromma', 149);
insert into CITY (City_ID, City_Name, Country_ID) values (458, 'Mikuni', 399);
insert into CITY (City_ID, City_Name, Country_ID) values (459, 'Guadalupe', 160);
insert into CITY (City_ID, City_Name, Country_ID) values (460, 'Czerwin', 108);
insert into CITY (City_ID, City_Name, Country_ID) values (461, 'Fosses', 290);
insert into CITY (City_ID, City_Name, Country_ID) values (462, 'Valongo', 70);
insert into CITY (City_ID, City_Name, Country_ID) values (463, 'Garden Grove', 396);
insert into CITY (City_ID, City_Name, Country_ID) values (464, 'Boyarka', 438);
insert into CITY (City_ID, City_Name, Country_ID) values (465, 'Topol’noye', 430);
insert into CITY (City_ID, City_Name, Country_ID) values (466, 'Xin’an', 380);
insert into CITY (City_ID, City_Name, Country_ID) values (467, 'Cafayate', 113);
insert into CITY (City_ID, City_Name, Country_ID) values (468, 'Wairinding', 384);
insert into CITY (City_ID, City_Name, Country_ID) values (469, 'Jingpeng', 377);
insert into CITY (City_ID, City_Name, Country_ID) values (470, 'Avelinha', 182);
insert into CITY (City_ID, City_Name, Country_ID) values (471, 'Daiyue', 146);
insert into CITY (City_ID, City_Name, Country_ID) values (472, 'Butungan', 227);
insert into CITY (City_ID, City_Name, Country_ID) values (473, 'Ledeč nad Sázavou', 109);
insert into CITY (City_ID, City_Name, Country_ID) values (474, 'Bélel', 193);
insert into CITY (City_ID, City_Name, Country_ID) values (475, 'Nzega', 109);
insert into CITY (City_ID, City_Name, Country_ID) values (476, 'Shekou', 272);
insert into CITY (City_ID, City_Name, Country_ID) values (477, 'Emiliano Zapata', 6);
insert into CITY (City_ID, City_Name, Country_ID) values (478, 'Damiao', 71);
insert into CITY (City_ID, City_Name, Country_ID) values (479, 'Lorena', 208);
insert into CITY (City_ID, City_Name, Country_ID) values (480, 'Kalpin', 498);
insert into CITY (City_ID, City_Name, Country_ID) values (481, 'Trenggulunan', 141);
insert into CITY (City_ID, City_Name, Country_ID) values (482, 'Bressuire', 357);
insert into CITY (City_ID, City_Name, Country_ID) values (483, 'Xiongzhou', 133);
insert into CITY (City_ID, City_Name, Country_ID) values (484, 'Koubia', 361);
insert into CITY (City_ID, City_Name, Country_ID) values (485, 'Cinunjang', 114);
insert into CITY (City_ID, City_Name, Country_ID) values (486, 'Paraíso', 287);
insert into CITY (City_ID, City_Name, Country_ID) values (487, 'Shiyu', 448);
insert into CITY (City_ID, City_Name, Country_ID) values (488, 'Savonranta', 493);
insert into CITY (City_ID, City_Name, Country_ID) values (489, 'Haparanda', 461);
insert into CITY (City_ID, City_Name, Country_ID) values (490, 'Garzón', 497);
insert into CITY (City_ID, City_Name, Country_ID) values (491, 'El Puerto', 216);
insert into CITY (City_ID, City_Name, Country_ID) values (492, 'Tianmen', 421);
insert into CITY (City_ID, City_Name, Country_ID) values (493, 'Mokwa', 469);
insert into CITY (City_ID, City_Name, Country_ID) values (494, 'Düsseldorf', 375);
insert into CITY (City_ID, City_Name, Country_ID) values (495, 'Masachapa', 211);
insert into CITY (City_ID, City_Name, Country_ID) values (496, 'Xinkaikou', 500);
insert into CITY (City_ID, City_Name, Country_ID) values (497, 'Cogon', 384);
insert into CITY (City_ID, City_Name, Country_ID) values (498, 'San Felipe Old', 429);
insert into CITY (City_ID, City_Name, Country_ID) values (499, 'Huadi', 123);
insert into CITY (City_ID, City_Name, Country_ID) values (500, 'Shen’ao', 468);
