insert into CITY (City_ID, City_Name, Country_ID) values (1, 'Tallinn', 1);
insert into CITY (City_ID, City_Name, Country_ID) values (2, 'Fier', 2);
insert into CITY (City_ID, City_Name, Country_ID) values (3, 'Chapimarca', 3);
insert into CITY (City_ID, City_Name, Country_ID) values (4, 'Kiiminki', 4);
insert into CITY (City_ID, City_Name, Country_ID) values (5, 'Langgen', 5);
insert into CITY (City_ID, City_Name, Country_ID) values (6, 'Pulupandan', 6);
insert into CITY (City_ID, City_Name, Country_ID) values (7, 'Bardiyā', 7);
insert into CITY (City_ID, City_Name, Country_ID) values (8, 'Qianfoling', 8);
insert into CITY (City_ID, City_Name, Country_ID) values (9, 'Naekan', 9);
insert into CITY (City_ID, City_Name, Country_ID) values (10, 'Rakiv Lis', 10);
insert into CITY (City_ID, City_Name, Country_ID) values (11, 'Emiliano Zapata', 11);
insert into CITY (City_ID, City_Name, Country_ID) values (12, 'Onsala', 12);
insert into CITY (City_ID, City_Name, Country_ID) values (13, 'Paradise', 13);
insert into CITY (City_ID, City_Name, Country_ID) values (14, 'Fenggang', 14);
insert into CITY (City_ID, City_Name, Country_ID) values (15, 'Tekes', 15);
insert into CITY (City_ID, City_Name, Country_ID) values (16, 'Jiangbu', 16);
insert into CITY (City_ID, City_Name, Country_ID) values (17, 'Socorro', 17);
insert into CITY (City_ID, City_Name, Country_ID) values (18, 'Xingong', 18);
insert into CITY (City_ID, City_Name, Country_ID) values (19, 'Anserma', 19);
insert into CITY (City_ID, City_Name, Country_ID) values (20, 'Novoye Leushino', 20);
insert into CITY (City_ID, City_Name, Country_ID) values (21, 'Jacura', 21);
insert into CITY (City_ID, City_Name, Country_ID) values (22, 'Kowale', 22);
insert into CITY (City_ID, City_Name, Country_ID) values (23, 'Jardim', 23);
insert into CITY (City_ID, City_Name, Country_ID) values (24, 'Samothráki', 24);
insert into CITY (City_ID, City_Name, Country_ID) values (25, 'Banqiao', 25);
insert into CITY (City_ID, City_Name, Country_ID) values (26, 'Puyang', 26);
insert into CITY (City_ID, City_Name, Country_ID) values (27, 'Krasnyy Yar', 27);
insert into CITY (City_ID, City_Name, Country_ID) values (28, 'Huntington', 28);
insert into CITY (City_ID, City_Name, Country_ID) values (29, 'Siao', 29);
insert into CITY (City_ID, City_Name, Country_ID) values (30, 'Krzyżanów', 30);
insert into CITY (City_ID, City_Name, Country_ID) values (31, 'Katoro', 31);
insert into CITY (City_ID, City_Name, Country_ID) values (32, 'Al Ḩāmūl', 32);
insert into CITY (City_ID, City_Name, Country_ID) values (33, 'Itajuípe', 33);
insert into CITY (City_ID, City_Name, Country_ID) values (34, 'Pescara', 34);
insert into CITY (City_ID, City_Name, Country_ID) values (35, 'Tlučná', 35);
insert into CITY (City_ID, City_Name, Country_ID) values (36, 'Kolchikón', 36);
insert into CITY (City_ID, City_Name, Country_ID) values (37, 'Zaklików', 37);
insert into CITY (City_ID, City_Name, Country_ID) values (38, 'Nangerang', 38);
insert into CITY (City_ID, City_Name, Country_ID) values (39, 'Doāba', 39);
insert into CITY (City_ID, City_Name, Country_ID) values (40, 'Jagüey Grande', 40);
insert into CITY (City_ID, City_Name, Country_ID) values (41, 'Puerto Boyacá', 41);
insert into CITY (City_ID, City_Name, Country_ID) values (42, 'Tulyushka', 42);
insert into CITY (City_ID, City_Name, Country_ID) values (43, 'Monkayo', 43);
insert into CITY (City_ID, City_Name, Country_ID) values (44, 'Vladimir', 44);
insert into CITY (City_ID, City_Name, Country_ID) values (45, 'Cibeureum Satu', 45);
insert into CITY (City_ID, City_Name, Country_ID) values (46, 'Libacao', 46);
insert into CITY (City_ID, City_Name, Country_ID) values (47, 'Marsada', 47);
insert into CITY (City_ID, City_Name, Country_ID) values (48, 'Lianghu', 48);
insert into CITY (City_ID, City_Name, Country_ID) values (49, 'Paris 13', 49);
insert into CITY (City_ID, City_Name, Country_ID) values (50, 'Hecun', 50);
insert into CITY (City_ID, City_Name, Country_ID) values (51, 'Khal’ch', 51);
insert into CITY (City_ID, City_Name, Country_ID) values (52, 'Hongjia', 52);
insert into CITY (City_ID, City_Name, Country_ID) values (53, 'Campamento', 53);
insert into CITY (City_ID, City_Name, Country_ID) values (54, 'Thị Trấn Nguyên Bình', 54);
insert into CITY (City_ID, City_Name, Country_ID) values (55, 'Debrecen', 55);
insert into CITY (City_ID, City_Name, Country_ID) values (56, 'Viengxay', 56);
insert into CITY (City_ID, City_Name, Country_ID) values (57, 'Huyuan', 57);
insert into CITY (City_ID, City_Name, Country_ID) values (58, 'Suizhong', 58);
insert into CITY (City_ID, City_Name, Country_ID) values (59, 'Buôn Ma Thuột', 59);
insert into CITY (City_ID, City_Name, Country_ID) values (60, 'Thung Yang Daeng', 60);
insert into CITY (City_ID, City_Name, Country_ID) values (61, 'Saku', 61);
insert into CITY (City_ID, City_Name, Country_ID) values (62, 'Buyunshan', 62);
insert into CITY (City_ID, City_Name, Country_ID) values (63, 'Detroit', 63);
insert into CITY (City_ID, City_Name, Country_ID) values (64, 'Biaokou', 64);
insert into CITY (City_ID, City_Name, Country_ID) values (65, 'Prado', 65);
insert into CITY (City_ID, City_Name, Country_ID) values (66, 'Fuxi', 66);
insert into CITY (City_ID, City_Name, Country_ID) values (67, 'Slobodskoy', 67);
insert into CITY (City_ID, City_Name, Country_ID) values (68, 'Ấp Tân Ngãi', 68);
insert into CITY (City_ID, City_Name, Country_ID) values (69, 'Oematnunu', 69);
insert into CITY (City_ID, City_Name, Country_ID) values (70, 'Meilin', 70);
insert into CITY (City_ID, City_Name, Country_ID) values (71, 'Daxi', 71);
insert into CITY (City_ID, City_Name, Country_ID) values (72, 'Haukivuori', 72);
insert into CITY (City_ID, City_Name, Country_ID) values (73, 'Viga', 73);
insert into CITY (City_ID, City_Name, Country_ID) values (74, 'Bafoussam', 74);
insert into CITY (City_ID, City_Name, Country_ID) values (75, 'Ban Nahin', 75);
insert into CITY (City_ID, City_Name, Country_ID) values (76, 'Stavyshche', 76);
insert into CITY (City_ID, City_Name, Country_ID) values (77, 'Khatsyezhyna', 77);
insert into CITY (City_ID, City_Name, Country_ID) values (78, 'Ciechocin', 78);
insert into CITY (City_ID, City_Name, Country_ID) values (79, 'Mercedes', 79);
insert into CITY (City_ID, City_Name, Country_ID) values (80, 'Quisqueya', 80);
insert into CITY (City_ID, City_Name, Country_ID) values (81, 'Notranje Gorice', 81);
insert into CITY (City_ID, City_Name, Country_ID) values (82, 'Jiangnan', 82);
insert into CITY (City_ID, City_Name, Country_ID) values (83, 'Krivodanovka', 83);
insert into CITY (City_ID, City_Name, Country_ID) values (84, 'Jixin', 84);
insert into CITY (City_ID, City_Name, Country_ID) values (85, 'Laborde', 85);
insert into CITY (City_ID, City_Name, Country_ID) values (86, 'Bāgh-e Maīdān', 86);
insert into CITY (City_ID, City_Name, Country_ID) values (87, 'El Alamo', 87);
insert into CITY (City_ID, City_Name, Country_ID) values (88, 'Mat-i', 88);
insert into CITY (City_ID, City_Name, Country_ID) values (89, 'Changfu', 89);
insert into CITY (City_ID, City_Name, Country_ID) values (90, 'Madalena', 90);
insert into CITY (City_ID, City_Name, Country_ID) values (91, 'Nador', 91);
insert into CITY (City_ID, City_Name, Country_ID) values (92, 'Córdoba', 92);
insert into CITY (City_ID, City_Name, Country_ID) values (93, 'Furukawa', 93);
insert into CITY (City_ID, City_Name, Country_ID) values (94, 'Pupiales', 94);
insert INTO CITY (City_ID, City_Name, Country_ID) values (95, 'Liaobu', 95);
insert INTO CITY (City_ID, City_Name, Country_ID) values (96, 'Paprotnia', 96);
insert INTO CITY (City_ID, City_Name, Country_ID) values (97, 'Villa Altagracia', 97);
insert INTO CITY (City_ID, City_Name, Country_ID) values (98, 'Bataiporã', 98);
insert INTO CITY (City_ID, City_Name, Country_ID) values (99, 'Huilongshan', 99);
insert INTO CITY (City_ID, City_Name, Country_ID) values (100, 'Tongtuan', 100);
insert INTO CITY (City_ID, City_Name, Country_ID) values (101, 'Harderwijk', 101);
insert INTO CITY (City_ID, City_Name, Country_ID) values (102, 'Paris 15', 102);
insert INTO CITY (City_ID, City_Name, Country_ID) values (103, 'San Jacinto', 103);
insert INTO CITY (City_ID, City_Name, Country_ID) values (104, 'Hamburg', 104);
insert INTO CITY (City_ID, City_Name, Country_ID) values (105, 'Khatsyezhyna', 105);
insert INTO CITY (City_ID, City_Name, Country_ID) values (106, 'Ōgaki', 106);
insert INTO CITY (City_ID, City_Name, Country_ID) values (107, 'Ruteng', 107);
insert INTO CITY (City_ID, City_Name, Country_ID) values (108, 'Socorro', 108);
insert INTO CITY (City_ID, City_Name, Country_ID) values (109, 'Gaojiabu', 109);
insert INTO CITY (City_ID, City_Name, Country_ID) values (110, 'Pardelhas', 110);
insert INTO CITY (City_ID, City_Name, Country_ID) values (111, 'Zruč nad Sázavou', 111);
insert INTO CITY (City_ID, City_Name, Country_ID) values (112, 'Melaka', 112);
insert INTO CITY (City_ID, City_Name, Country_ID) values (113, 'Ashgabat', 113);
insert INTO CITY (City_ID, City_Name, Country_ID) values (114, 'Tefé', 114);
insert INTO CITY (City_ID, City_Name, Country_ID) values (115, 'Xingdian', 115);
insert INTO CITY (City_ID, City_Name, Country_ID) values (116, 'Caibarién', 116);
insert INTO CITY (City_ID, City_Name, Country_ID) values (117, 'Uglich', 117);
insert INTO CITY (City_ID, City_Name, Country_ID) values (118, 'Dresden', 118);
insert INTO CITY (City_ID, City_Name, Country_ID) values (119, 'Hepingyizu', 119);
insert INTO CITY (City_ID, City_Name, Country_ID) values (120, 'Thabazimbi', 120);
insert INTO CITY (City_ID, City_Name, Country_ID) values (121, 'Pindushi', 121);
insert INTO CITY (City_ID, City_Name, Country_ID) values (122, 'Thulamahashi', 122);
insert INTO CITY (City_ID, City_Name, Country_ID) values (123, 'Blerim', 123);
insert INTO CITY (City_ID, City_Name, Country_ID) values (124, 'Soloma', 124);
insert INTO CITY (City_ID, City_Name, Country_ID) values (125, 'Yeniugou', 125);
insert INTO CITY (City_ID, City_Name, Country_ID) values (126, 'Juzhen', 126);
insert INTO CITY (City_ID, City_Name, Country_ID) values (127, 'Rokiciny', 127);
insert INTO CITY (City_ID, City_Name, Country_ID) values (128, 'Yangshan', 128);
insert INTO CITY (City_ID, City_Name, Country_ID) values (129, 'Al Wardānīn', 129);
insert INTO CITY (City_ID, City_Name, Country_ID) values (130, 'Sausa', 130);
insert INTO CITY (City_ID, City_Name, Country_ID) values (131, 'Energeticheskiy', 131);
insert INTO CITY (City_ID, City_Name, Country_ID) values (132, 'Sariwŏn', 132);
insert INTO CITY (City_ID, City_Name, Country_ID) values (133, 'Chornyanka', 133);
insert INTO CITY (City_ID, City_Name, Country_ID) values (134, 'Áno Kopanákion', 134);
insert INTO CITY (City_ID, City_Name, Country_ID) values (135, 'Najd al Jumā‘ī', 135);
insert INTO CITY (City_ID, City_Name, Country_ID) values (136, 'Banyue', 136);
insert INTO CITY (City_ID, City_Name, Country_ID) values (137, 'Mundolsheim', 137);
insert INTO CITY (City_ID, City_Name, Country_ID) values (138, 'Sobreira', 138);
insert INTO CITY (City_ID, City_Name, Country_ID) values (139, 'Jinxiang', 139);
insert INTO CITY (City_ID, City_Name, Country_ID) values (140, 'Vónitsa', 140);
insert INTO CITY (City_ID, City_Name, Country_ID) values (141, 'Tchintabaraden', 141);
insert INTO CITY (City_ID, City_Name, Country_ID) values (142, 'Dolní Dunajovice', 142);
insert INTO CITY (City_ID, City_Name, Country_ID) values (143, 'Ponta do Sol', 143);
insert INTO CITY (City_ID, City_Name, Country_ID) values (144, 'Amadora', 144);
insert INTO CITY (City_ID, City_Name, Country_ID) values (145, 'Włosienica', 145);
insert INTO CITY (City_ID, City_Name, Country_ID) values (146, 'Makato', 146);
insert INTO CITY (City_ID, City_Name, Country_ID) values (147, 'Beishan', 147);
insert INTO CITY (City_ID, City_Name, Country_ID) values (148, 'Beberibe', 148);
insert INTO CITY (City_ID, City_Name, Country_ID) values (149, 'Huntington', 149);
insert INTO CITY (City_ID, City_Name, Country_ID) values (150, 'Even Yehuda', 150);
insert INTO CITY (City_ID, City_Name, Country_ID) values (151, 'Santo António da Charneca', 151);
insert INTO CITY (City_ID, City_Name, Country_ID) values (152, 'Kiritsy', 152);
insert INTO CITY (City_ID, City_Name, Country_ID) values (153, 'Paris 09', 153);
insert INTO CITY (City_ID, City_Name, Country_ID) values (154, 'Akkol’', 154);
insert INTO CITY (City_ID, City_Name, Country_ID) values (155, 'Qiancang', 155);
insert INTO CITY (City_ID, City_Name, Country_ID) values (156, 'Phu Kam Yao', 156);
insert INTO CITY (City_ID, City_Name, Country_ID) values (157, 'Libon', 157);
insert INTO CITY (City_ID, City_Name, Country_ID) values (158, 'Furmanov', 158);
insert INTO CITY (City_ID, City_Name, Country_ID) values (159, 'Dijon', 159);
insert INTO CITY (City_ID, City_Name, Country_ID) values (160, 'Kalýves Polygýrou', 160);
insert INTO CITY (City_ID, City_Name, Country_ID) values (161, 'Cunliji', 161);
insert INTO CITY (City_ID, City_Name, Country_ID) values (162, 'Kedawung', 162);
insert INTO CITY (City_ID, City_Name, Country_ID) values (163, 'Lop', 163);
insert INTO CITY (City_ID, City_Name, Country_ID) values (164, 'Uzhhorod', 164);
insert INTO CITY (City_ID, City_Name, Country_ID) values (165, 'Catabola', 165);
insert INTO CITY (City_ID, City_Name, Country_ID) values (166, 'Bulalacao', 166);
insert INTO CITY (City_ID, City_Name, Country_ID) values (167, 'Timpas', 167);
insert INTO CITY (City_ID, City_Name, Country_ID) values (168, 'La Carlota', 168);
insert INTO CITY (City_ID, City_Name, Country_ID) values (169, 'Libato', 169);
insert INTO CITY (City_ID, City_Name, Country_ID) values (170, 'Hongqiao', 170);
insert INTO CITY (City_ID, City_Name, Country_ID) values (171, 'Omsk', 171);
insert INTO CITY (City_ID, City_Name, Country_ID) values (172, 'Atlanta', 172);
insert INTO CITY (City_ID, City_Name, Country_ID) values (173, 'Zlatni Pyasatsi', 173);
insert INTO CITY (City_ID, City_Name, Country_ID) values (174, 'Voznesenskaya', 174);
insert INTO CITY (City_ID, City_Name, Country_ID) values (175, 'Padangulaktanding', 175);
insert INTO CITY (City_ID, City_Name, Country_ID) values (176, 'Andros Town', 176);
insert INTO CITY (City_ID, City_Name, Country_ID) values (177, 'Comalapa', 177);
insert INTO CITY (City_ID, City_Name, Country_ID) values (178, 'Apaga', 178);
insert INTO CITY (City_ID, City_Name, Country_ID) values (179, 'Quimistán', 179);
insert INTO CITY (City_ID, City_Name, Country_ID) values (180, 'Jagabaya Dua', 180);
insert INTO CITY (City_ID, City_Name, Country_ID) values (181, 'Sampacho', 181);
insert INTO CITY (City_ID, City_Name, Country_ID) values (182, 'Khāngāh Dogrān', 182);
insert INTO CITY (City_ID, City_Name, Country_ID) values (183, 'Xiangba', 183);
insert INTO CITY (City_ID, City_Name, Country_ID) values (184, 'Oygon', 184);
insert INTO CITY (City_ID, City_Name, Country_ID) values (185, 'Sucre', 185);
insert INTO CITY (City_ID, City_Name, Country_ID) values (186, 'Centar Župa', 186);
insert INTO CITY (City_ID, City_Name, Country_ID) values (187, 'San Pedro', 187);
insert INTO CITY (City_ID, City_Name, Country_ID) values (188, 'Hebeitun', 188);
insert INTO CITY (City_ID, City_Name, Country_ID) values (189, 'Florence', 189);
insert INTO CITY (City_ID, City_Name, Country_ID) values (190, 'Jinshan', 190);
insert INTO CITY (City_ID, City_Name, Country_ID) values (191, 'Jiaokui', 191);
insert INTO CITY (City_ID, City_Name, Country_ID) values (192, 'Sobreira', 192);
insert INTO CITY (City_ID, City_Name, Country_ID) values (193, 'Roma', 193);
insert INTO CITY (City_ID, City_Name, Country_ID) values (194, 'Orléans', 194);
insert INTO CITY (City_ID, City_Name, Country_ID) values (195, 'Chugay', 195);
insert INTO CITY (City_ID, City_Name, Country_ID) values (196, 'Zhantang', 1);
insert INTO CITY (City_ID, City_Name, Country_ID) values (197, 'Olutanga', 2);
insert INTO CITY (City_ID, City_Name, Country_ID) values (198, 'Wujingfu', 3);
insert INTO CITY (City_ID, City_Name, Country_ID) values (199, 'Camilaca', 4);
insert INTO CITY (City_ID, City_Name, Country_ID) values (200, 'Domsjö', 5);
insert INTO CITY (City_ID, City_Name, Country_ID) values (201, 'Santa Elena', 6);
insert INTO CITY (City_ID, City_Name, Country_ID) values (202, 'Zhaixi', 7);
insert INTO CITY (City_ID, City_Name, Country_ID) values (203, 'Yenagoa', 8);
insert INTO CITY (City_ID, City_Name, Country_ID) values (204, 'Konārak', 9);
insert INTO CITY (City_ID, City_Name, Country_ID) values (205, 'Imsida', 10);
insert INTO CITY (City_ID, City_Name, Country_ID) values (206, 'Macroom', 11);
insert INTO CITY (City_ID, City_Name, Country_ID) values (207, 'Itatuba', 12);
insert INTO CITY (City_ID, City_Name, Country_ID) values (208, 'Roanoke', 13);
insert INTO CITY (City_ID, City_Name, Country_ID) values (209, 'Chayek', 14);
insert INTO CITY (City_ID, City_Name, Country_ID) values (210, 'Candijay', 15);
insert INTO CITY (City_ID, City_Name, Country_ID) values (211, 'Patos Fshat', 16);
insert INTO CITY (City_ID, City_Name, Country_ID) values (212, 'Puji', 17);
insert INTO CITY (City_ID, City_Name, Country_ID) values (213, 'Cilegi', 18);
insert INTO CITY (City_ID, City_Name, Country_ID) values (214, 'Leuwidamar', 19);
insert INTO CITY (City_ID, City_Name, Country_ID) values (215, 'Ma’ao', 20);
insert INTO CITY (City_ID, City_Name, Country_ID) values (216, 'Poli', 21);
insert INTO CITY (City_ID, City_Name, Country_ID) values (217, 'Yala', 22);
insert INTO CITY (City_ID, City_Name, Country_ID) values (218, 'Changqiao', 23);
insert INTO CITY (City_ID, City_Name, Country_ID) values (219, 'Nekrasovka', 24);
insert INTO CITY (City_ID, City_Name, Country_ID) values (220, 'Uralets', 25);
insert INTO CITY (City_ID, City_Name, Country_ID) values (221, 'Uruguaiana', 26);
insert INTO CITY (City_ID, City_Name, Country_ID) values (222, 'Amgalang', 27);
insert INTO CITY (City_ID, City_Name, Country_ID) values (223, 'Banshu', 28);
insert INTO CITY (City_ID, City_Name, Country_ID) values (224, 'Lewo', 29);
insert INTO CITY (City_ID, City_Name, Country_ID) values (225, 'Hanggan', 30);
insert INTO CITY (City_ID, City_Name, Country_ID) values (226, 'Saint-Raymond', 31);
insert INTO CITY (City_ID, City_Name, Country_ID) values (227, 'Sukhobezvodnoye', 32);
insert INTO CITY (City_ID, City_Name, Country_ID) values (228, 'Herong', 33);
insert INTO CITY (City_ID, City_Name, Country_ID) values (229, 'Amieira', 34);
insert INTO CITY (City_ID, City_Name, Country_ID) values (230, 'Ypacarai', 35);
insert INTO CITY (City_ID, City_Name, Country_ID) values (231, 'Anren', 36);
insert INTO CITY (City_ID, City_Name, Country_ID) values (232, 'Tocota', 37);
insert INTO CITY (City_ID, City_Name, Country_ID) values (233, 'Valence', 38);
insert INTO CITY (City_ID, City_Name, Country_ID) values (234, 'Amarillo', 39);
insert INTO CITY (City_ID, City_Name, Country_ID) values (235, 'Bungtiang Barat', 40);
insert INTO CITY (City_ID, City_Name, Country_ID) values (236, 'Bender', 41);
insert INTO CITY (City_ID, City_Name, Country_ID) values (237, 'Pindi Gheb', 42);
insert INTO CITY (City_ID, City_Name, Country_ID) values (238, 'Xincheng', 43);
insert INTO CITY (City_ID, City_Name, Country_ID) values (239, 'Valdivia', 44);
insert INTO CITY (City_ID, City_Name, Country_ID) values (240, 'Denver', 45);
insert INTO CITY (City_ID, City_Name, Country_ID) values (241, 'Manukau City', 46);
insert INTO CITY (City_ID, City_Name, Country_ID) values (242, 'Al Fūlah', 47);
insert INTO CITY (City_ID, City_Name, Country_ID) values (243, 'Abrantes', 48);
insert INTO CITY (City_ID, City_Name, Country_ID) values (244, 'Daduo', 49);
insert INTO CITY (City_ID, City_Name, Country_ID) values (245, 'Daminggong', 50);
insert INTO CITY (City_ID, City_Name, Country_ID) values (246, 'Descalvado', 51);
insert INTO CITY (City_ID, City_Name, Country_ID) values (247, 'Ajung', 52);
insert INTO CITY (City_ID, City_Name, Country_ID) values (248, 'Mindupok', 53);
insert INTO CITY (City_ID, City_Name, Country_ID) values (249, 'Yantian', 54);
insert INTO CITY (City_ID, City_Name, Country_ID) values (250, 'Klimontów', 55);
insert INTO CITY (City_ID, City_Name, Country_ID) values (251, 'Krzanowice', 56);
insert INTO CITY (City_ID, City_Name, Country_ID) values (252, 'Meshcherino', 57);
insert INTO CITY (City_ID, City_Name, Country_ID) values (253, 'Yushan', 58);
insert INTO CITY (City_ID, City_Name, Country_ID) values (254, 'Теארצה', 59);
insert INTO CITY (City_ID, City_Name, Country_ID) values (255, 'Wysoka', 60);
insert INTO CITY (City_ID, City_Name, Country_ID) values (256, 'Linzi', 61);
insert INTO CITY (City_ID, City_Name, Country_ID) values (257, 'Pak Phanang', 62);
insert INTO CITY (City_ID, City_Name, Country_ID) values (258, 'Lamalera', 63);
insert INTO CITY (City_ID, City_Name, Country_ID) values (259, 'Miliangju', 64);
insert INTO CITY (City_ID, City_Name, Country_ID) values (260, 'Anbyŏn-ŭp', 65);
insert INTO CITY (City_ID, City_Name, Country_ID) values (261, 'Fanzeres', 66);
insert INTO CITY (City_ID, City_Name, Country_ID) values (262, 'Krajan', 67);
insert INTO CITY (City_ID, City_Name, Country_ID) values (263, 'Pernå', 68);
insert INTO CITY (City_ID, City_Name, Country_ID) values (264, 'Tayum', 69);
insert INTO CITY (City_ID, City_Name, Country_ID) values (265, 'Khelyulya', 70);
insert INTO CITY (City_ID, City_Name, Country_ID) values (266, 'Tsuma', 71);
insert INTO CITY (City_ID, City_Name, Country_ID) values (267, 'Gunjur Kuta', 72);
insert INTO CITY (City_ID, City_Name, Country_ID) values (268, 'Cuyotenango', 73);
insert INTO CITY (City_ID, City_Name, Country_ID) values (269, 'Néos Skopós', 74);
insert INTO CITY (City_ID, City_Name, Country_ID) values (270, 'Huicheng', 75);
insert INTO CITY (City_ID, City_Name, Country_ID) values (271, 'Cipanas', 76);
insert INTO CITY (City_ID, City_Name, Country_ID) values (272, 'Haodian', 77);
insert INTO CITY (City_ID, City_Name, Country_ID) values (273, 'Waiholo', 78);
insert INTO CITY (City_ID, City_Name, Country_ID) values (274, 'Zhouzai', 79);
insert INTO CITY (City_ID, City_Name, Country_ID) values (275, 'Balahovit', 80);
insert INTO CITY (City_ID, City_Name, Country_ID) values (276, 'Dampit', 81);
insert INTO CITY (City_ID, City_Name, Country_ID) values (277, 'Yuezhao', 82);
insert INTO CITY (City_ID, City_Name, Country_ID) values (278, 'As Suqaylibīyah', 83);
insert INTO CITY (City_ID, City_Name, Country_ID) values (279, 'Carregado', 84);
insert INTO CITY (City_ID, City_Name, Country_ID) values (280, 'Złotów', 85);
insert INTO CITY (City_ID, City_Name, Country_ID) values (281, 'Dandai', 86);
insert INTO CITY (City_ID, City_Name, Country_ID) values (282, 'San Antonio', 87);
insert INTO CITY (City_ID, City_Name, Country_ID) values (283, 'Brunssum', 88);
insert INTO CITY (City_ID, City_Name, Country_ID) values (284, 'Chřibská', 89);
insert INTO CITY (City_ID, City_Name, Country_ID) values (285, 'Seda', 90);
insert INTO CITY (City_ID, City_Name, Country_ID) values (286, 'Astypálaia', 91);
insert INTO CITY (City_ID, City_Name, Country_ID) values (287, 'Ulashan', 92);
insert INTO CITY (City_ID, City_Name, Country_ID) values (288, 'Hampton', 93);
insert INTO CITY (City_ID, City_Name, Country_ID) values (289, 'Huadi', 94);
insert INTO CITY (City_ID, City_Name, Country_ID) values (290, 'Sokyryany', 95);
insert INTO CITY (City_ID, City_Name, Country_ID) values (291, 'Gasri', 96);
insert INTO CITY (City_ID, City_Name, Country_ID) values (292, 'Bukonyo', 97);
insert INTO CITY (City_ID, City_Name, Country_ID) values (293, 'Şurmān', 98);
insert INTO CITY (City_ID, City_Name, Country_ID) values (294, 'Águas Vermelhas', 99);
insert INTO CITY (City_ID, City_Name, Country_ID) values (295, 'Yŏnmu', 100);
insert INTO CITY (City_ID, City_Name, Country_ID) values (296, 'Sukodono', 101);
insert INTO CITY (City_ID, City_Name, Country_ID) values (297, 'København', 102);
insert INTO CITY (City_ID, City_Name, Country_ID) values (298, 'Mashui', 103);
insert INTO CITY (City_ID, City_Name, Country_ID) values (299, 'Tegalgunung', 104);
insert INTO CITY (City_ID, City_Name, Country_ID) values (300, 'Bangko', 105);
insert INTO CITY (City_ID, City_Name, Country_ID) values (301, 'Lashma', 106);
insert INTO CITY (City_ID, City_Name, Country_ID) values (302, 'Velká Dobrá', 107);
insert INTO CITY (City_ID, City_Name, Country_ID) values (303, 'Toupopu', 108);
insert INTO CITY (City_ID, City_Name, Country_ID) values (304, 'Zoumi', 109);
insert INTO CITY (City_ID, City_Name, Country_ID) values (305, 'Matina', 110);
insert INTO CITY (City_ID, City_Name, Country_ID) values (306, 'Sedatigede', 111);
insert INTO CITY (City_ID, City_Name, Country_ID) values (307, 'Älmhult', 112);
insert INTO CITY (City_ID, City_Name, Country_ID) values (308, 'San Francisco', 113);
insert INTO CITY (City_ID, City_Name, Country_ID) values (309, 'Campo Largo', 114);
insert INTO CITY (City_ID, City_Name, Country_ID) values (310, 'Anqing', 115);
insert INTO CITY (City_ID, City_Name, Country_ID) values (311, 'Iizuka', 116);
insert INTO CITY (City_ID, City_Name, Country_ID) values (312, 'Banyutengah', 117);
insert INTO CITY (City_ID, City_Name, Country_ID) values (313, 'Hantsavichy', 118);
insert INTO CITY (City_ID, City_Name, Country_ID) values (314, 'Luntai', 119);
insert INTO CITY (City_ID, City_Name, Country_ID) values (315, 'Gaoyi', 120);
insert INTO CITY (City_ID, City_Name, Country_ID) values (316, 'Callahuanca', 121);
insert INTO CITY (City_ID, City_Name, Country_ID) values (317, 'Majunying', 122);
insert INTO CITY (City_ID, City_Name, Country_ID) values (318, 'Bukuru', 123);
insert INTO CITY (City_ID, City_Name, Country_ID) values (319, 'Jiuxian', 124);
insert INTO CITY (City_ID, City_Name, Country_ID) values (320, 'Gose', 125);
insert INTO CITY (City_ID, City_Name, Country_ID) values (321, 'Yingmaili', 126);
insert INTO CITY (City_ID, City_Name, Country_ID) values (322, 'Lennec', 127);
insert INTO CITY (City_ID, City_Name, Country_ID) values (323, 'Tutayev', 128);
insert INTO CITY (City_ID, City_Name, Country_ID) values (324, 'Konga', 129);
insert INTO CITY (City_ID, City_Name, Country_ID) values (325, 'Micheng', 130);
insert INTO CITY (City_ID, City_Name, Country_ID) values (326, 'Xarsingma', 131);
insert INTO CITY (City_ID, City_Name, Country_ID) values (327, 'Yangdu', 132);
insert INTO CITY (City_ID, City_Name, Country_ID) values (328, 'Xidajie', 133);
insert INTO CITY (City_ID, City_Name, Country_ID) values (329, 'Xingang', 134);
insert INTO CITY (City_ID, City_Name, Country_ID) values (330, 'Derzhavīnsk', 135);
insert INTO CITY (City_ID, City_Name, Country_ID) values (331, 'Qaffīn', 136);
insert INTO CITY (City_ID, City_Name, Country_ID) values (332, 'Pexiligais', 137);
insert INTO CITY (City_ID, City_Name, Country_ID) values (333, 'Dairiti', 138);
insert INTO CITY (City_ID, City_Name, Country_ID) values (334, 'Āsasa', 139);
insert INTO CITY (City_ID, City_Name, Country_ID) values (335, 'Leuwayang', 140);
insert INTO CITY (City_ID, City_Name, Country_ID) values (336, 'Ińsko', 141);
insert INTO CITY (City_ID, City_Name, Country_ID) values (337, 'Kisela Voda', 142);
insert INTO CITY (City_ID, City_Name, Country_ID) values (338, 'Bobrov', 143);
insert INTO CITY (City_ID, City_Name, Country_ID) values (339, 'Kawęczyn', 144);
insert INTO CITY (City_ID, City_Name, Country_ID) values (340, 'Bojongsarung', 145);
insert INTO CITY (City_ID, City_Name, Country_ID) values (341, 'Alcaria', 146);
insert INTO CITY (City_ID, City_Name, Country_ID) values (342, 'Troyan', 147);
insert INTO CITY (City_ID, City_Name, Country_ID) values (343, 'Marcala', 148);
insert INTO CITY (City_ID, City_Name, Country_ID) values (344, 'Primošten', 149);
insert INTO CITY (City_ID, City_Name, Country_ID) values (345, 'Skien', 150);
insert INTO CITY (City_ID, City_Name, Country_ID) values (346, 'Togu', 151);
insert INTO CITY (City_ID, City_Name, Country_ID) values (347, 'Ipoh', 152);
insert INTO CITY (City_ID, City_Name, Country_ID) values (348, 'Armavir', 153);
insert INTO CITY (City_ID, City_Name, Country_ID) values (349, 'Méru', 154);
insert INTO CITY (City_ID, City_Name, Country_ID) values (350, 'Gllogjan', 155);
insert INTO CITY (City_ID, City_Name, Country_ID) values (351, 'Gorno Orizari', 156);
insert INTO CITY (City_ID, City_Name, Country_ID) values (352, 'Ludvika', 157);
insert INTO CITY (City_ID, City_Name, Country_ID) values (353, 'Serednye', 158);
insert INTO CITY (City_ID, City_Name, Country_ID) values (354, 'Mogapi', 159);
insert INTO CITY (City_ID, City_Name, Country_ID) values (355, 'Tonj', 160);
insert INTO CITY (City_ID, City_Name, Country_ID) values (356, 'Bolinao', 161);
insert INTO CITY (City_ID, City_Name, Country_ID) values (357, 'Kaputian', 162);
insert INTO CITY (City_ID, City_Name, Country_ID) values (358, 'Yuezhao', 163);
insert INTO CITY (City_ID, City_Name, Country_ID) values (359, 'Bribir', 164);
insert INTO CITY (City_ID, City_Name, Country_ID) values (360, 'Tenri', 165);
insert INTO CITY (City_ID, City_Name, Country_ID) values (361, 'Jinqiao', 166);
insert INTO CITY (City_ID, City_Name, Country_ID) values (362, 'Pubu', 167);
insert INTO CITY (City_ID, City_Name, Country_ID) values (363, 'Juan N Alvarez', 168);
insert INTO CITY (City_ID, City_Name, Country_ID) values (364, 'Koygorodok', 169);
insert INTO CITY (City_ID, City_Name, Country_ID) values (365, 'El Zapote', 170);
insert INTO CITY (City_ID, City_Name, Country_ID) values (366, 'Mitrópoli', 171);
insert INTO CITY (City_ID, City_Name, Country_ID) values (367, 'Yucun', 172);
insert INTO CITY (City_ID, City_Name, Country_ID) values (368, 'Maisons-Laffitte', 173);
insert INTO CITY (City_ID, City_Name, Country_ID) values (369, 'Telengsari', 174);
insert INTO CITY (City_ID, City_Name, Country_ID) values (370, 'Niandui', 175);
insert INTO CITY (City_ID, City_Name, Country_ID) values (371, 'Tingloy', 176);
insert INTO CITY (City_ID, City_Name, Country_ID) values (372, 'Xinmin', 177);
insert INTO CITY (City_ID, City_Name, Country_ID) values (373, 'Omaha', 178);
insert INTO CITY (City_ID, City_Name, Country_ID) values (374, 'Bureng', 179);
insert INTO CITY (City_ID, City_Name, Country_ID) values (375, 'Dārayyā', 180);
insert INTO CITY (City_ID, City_Name, Country_ID) values (376, 'Dasanlian Lauk', 181);
insert INTO CITY (City_ID, City_Name, Country_ID) values (377, 'La Reforma', 182);
insert INTO CITY (City_ID, City_Name, Country_ID) values (378, 'Baiguo', 183);
insert INTO CITY (City_ID, City_Name, Country_ID) values (379, 'Iwaki', 184);
insert INTO CITY (City_ID, City_Name, Country_ID) values (380, 'Araras', 185);
insert INTO CITY (City_ID, City_Name, Country_ID) values (381, 'Wanareja', 186);
insert INTO CITY (City_ID, City_Name, Country_ID) values (382, 'Kuala Tuha', 187);
insert INTO CITY (City_ID, City_Name, Country_ID) values (383, 'Kota Kinabalu', 188);
insert INTO CITY (City_ID, City_Name, Country_ID) values (384, 'Duszniki-Zdrój', 189);
insert INTO CITY (City_ID, City_Name, Country_ID) values (385, 'Cabra Figa', 190);
insert INTO CITY (City_ID, City_Name, Country_ID) values (386, 'Chornoliztsi', 191);
insert INTO CITY (City_ID, City_Name, Country_ID) values (387, 'Outeiro', 192);
insert INTO CITY (City_ID, City_Name, Country_ID) values (388, 'Longmen', 193);
insert INTO CITY (City_ID, City_Name, Country_ID) values (389, 'Vysoké nad Jizerou', 194);
insert INTO CITY (City_ID, City_Name, Country_ID) values (390, 'Rada Tilly', 195);
insert INTO CITY (City_ID, City_Name, Country_ID) values (391, 'Shuangxiqiao', 1);
insert INTO CITY (City_ID, City_Name, Country_ID) values (392, 'El Zulia', 2);
insert INTO CITY (City_ID, City_Name, Country_ID) values (393, 'Fajã de Cima', 3);
insert INTO CITY (City_ID, City_Name, Country_ID) values (394, 'Avignon', 4);
insert INTO CITY (City_ID, City_Name, Country_ID) values (395, 'Bantacan', 5);
insert INTO CITY (City_ID, City_Name, Country_ID) values (396, 'Hammam Sousse', 6);
insert INTO CITY (City_ID, City_Name, Country_ID) values (397, 'Dodol', 7);
insert INTO CITY (City_ID, City_Name, Country_ID) values (398, 'Singkup', 8);
insert INTO CITY (City_ID, City_Name, Country_ID) values (399, 'Rio Grande', 9);
insert INTO CITY (City_ID, City_Name, Country_ID) values (400, 'Shuntian', 10);
insert INTO CITY (City_ID, City_Name, Country_ID) values (401, 'Oullins', 11);
insert INTO CITY (City_ID, City_Name, Country_ID) values (402, 'Suvorovskaya', 12);
insert INTO CITY (City_ID, City_Name, Country_ID) values (403, 'Santa Cruz De Tenerife', 13);
insert INTO CITY (City_ID, City_Name, Country_ID) values (404, 'Forshaga', 14);
insert INTO CITY (City_ID, City_Name, Country_ID) values (405, 'Qiankou', 15);
insert INTO CITY (City_ID, City_Name, Country_ID) values (406, 'Santa Marta de Penaguião', 16);
insert INTO CITY (City_ID, City_Name, Country_ID) values (407, 'Szczawnica', 17);
insert INTO CITY (City_ID, City_Name, Country_ID) values (408, 'Xiyuan', 18);
insert INTO CITY (City_ID, City_Name, Country_ID) values (409, 'Krzynowłoga Mała', 19);
insert INTO CITY (City_ID, City_Name, Country_ID) values (410, 'Huallanca', 20);
insert INTO CITY (City_ID, City_Name, Country_ID) values (411, 'Wuying', 21);
insert INTO CITY (City_ID, City_Name, Country_ID) values (412, 'Shuanglongchang', 22);
insert INTO CITY (City_ID, City_Name, Country_ID) values (413, 'Lazaro Cardenas', 23);
insert INTO CITY (City_ID, City_Name, Country_ID) values (414, 'Luozhou', 24);
insert INTO CITY (City_ID, City_Name, Country_ID) values (415, 'Jiujianfang', 25);
insert INTO CITY (City_ID, City_Name, Country_ID) values (416, 'Watuka', 26);
insert INTO CITY (City_ID, City_Name, Country_ID) values (417, 'La Libertad', 27);
insert INTO CITY (City_ID, City_Name, Country_ID) values (418, 'Futian', 28);
insert INTO CITY (City_ID, City_Name, Country_ID) values (419, 'Hedong', 29);
insert INTO CITY (City_ID, City_Name, Country_ID) values (420, 'Fonseca', 30);
insert INTO CITY (City_ID, City_Name, Country_ID) values (421, 'Brändö', 31);
insert INTO CITY (City_ID, City_Name, Country_ID) values (422, 'Mikumi', 32);
insert INTO CITY (City_ID, City_Name, Country_ID) values (423, 'Seongnam-si', 33);
insert INTO CITY (City_ID, City_Name, Country_ID) values (424, 'Huage', 34);
insert INTO CITY (City_ID, City_Name, Country_ID) values (425, 'Dunkerque', 35);
insert INTO CITY (City_ID, City_Name, Country_ID) values (426, 'Xiangcheng', 36);
insert INTO CITY (City_ID, City_Name, Country_ID) values (427, 'Chengguan', 37);
insert INTO CITY (City_ID, City_Name, Country_ID) values (428, 'Mīāndoāb', 38);
insert INTO CITY (City_ID, City_Name, Country_ID) values (429, 'Arnelas', 39);
insert INTO CITY (City_ID, City_Name, Country_ID) values (430, 'Yoshkar-Ola', 40);
insert INTO CITY (City_ID, City_Name, Country_ID) values (431, 'Binitayan', 41);
insert INTO CITY (City_ID, City_Name, Country_ID) values (432, 'Gordeyevka', 42);
insert INTO CITY (City_ID, City_Name, Country_ID) values (433, 'La Rochelle', 43);
insert INTO CITY (City_ID, City_Name, Country_ID) values (434, 'Kuala Lumpur', 44);
insert INTO CITY (City_ID, City_Name, Country_ID) values (435, 'Pajarillo', 45);
insert INTO CITY (City_ID, City_Name, Country_ID) values (436, 'Hudson Bay', 46);
insert INTO CITY (City_ID, City_Name, Country_ID) values (437, 'Kasreman Wetan', 47);
insert INTO CITY (City_ID, City_Name, Country_ID) values (438, 'Cihaur', 48);
insert INTO CITY (City_ID, City_Name, Country_ID) values (439, 'Jilma', 49);
insert INTO CITY (City_ID, City_Name, Country_ID) values (440, 'Cayenne', 50);
insert INTO CITY (City_ID, City_Name, Country_ID) values (441, 'Alingsås', 51);
insert INTO CITY (City_ID, City_Name, Country_ID) values (442, 'Dessalines', 52);
insert INTO CITY (City_ID, City_Name, Country_ID) values (443, 'Bagikkedok Lauk', 53);
insert INTO CITY (City_ID, City_Name, Country_ID) values (444, 'Poxin', 54);
insert INTO CITY (City_ID, City_Name, Country_ID) values (445, 'Santiago', 55);
insert INTO CITY (City_ID, City_Name, Country_ID) values (446, 'Druju', 56);
insert INTO CITY (City_ID, City_Name, Country_ID) values (447, 'Ar Rābiyah', 57);
insert INTO CITY (City_ID, City_Name, Country_ID) values (448, 'Wanfang', 58);
insert INTO CITY (City_ID, City_Name, Country_ID) values (449, 'Xingou', 59);
insert INTO CITY (City_ID, City_Name, Country_ID) values (450, 'Caobi', 60);
insert INTO CITY (City_ID, City_Name, Country_ID) values (451, 'Huaitu', 61);
insert INTO CITY (City_ID, City_Name, Country_ID) values (452, 'Gračanica', 62);
insert INTO CITY (City_ID, City_Name, Country_ID) values (453, 'Ilioúpoli', 63);
insert INTO CITY (City_ID, City_Name, Country_ID) values (454, 'Sukamulya', 64);
insert INTO CITY (City_ID, City_Name, Country_ID) values (455, 'Sinjār', 65);
insert INTO CITY (City_ID, City_Name, Country_ID) values (456, 'Pazarić', 66);
insert INTO CITY (City_ID, City_Name, Country_ID) values (457, 'Bromma', 67);
insert INTO CITY (City_ID, City_Name, Country_ID) values (458, 'Mikuni', 68);
insert INTO CITY (City_ID, City_Name, Country_ID) values (459, 'Guadalupe', 69);
insert INTO CITY (City_ID, City_Name, Country_ID) values (460, 'Czerwin', 70);
insert INTO CITY (City_ID, City_Name, Country_ID) values (461, 'Fosses', 71);
insert INTO CITY (City_ID, City_Name, Country_ID) values (462, 'Valongo', 72);
insert INTO CITY (City_ID, City_Name, Country_ID) values (463, 'Garden Grove', 73);
insert INTO CITY (City_ID, City_Name, Country_ID) values (464, 'Boyarka', 74);
insert INTO CITY (City_ID, City_Name, Country_ID) values (465, 'Topol’noye', 75);
insert INTO CITY (City_ID, City_Name, Country_ID) values (466, 'Xin’an', 76);
insert INTO CITY (City_ID, City_Name, Country_ID) values (467, 'Cafayate', 77);
insert INTO CITY (City_ID, City_Name, Country_ID) values (468, 'Wairinding', 78);
insert INTO CITY (City_ID, City_Name, Country_ID) values (469, 'Jingpeng', 79);
insert INTO CITY (City_ID, City_Name, Country_ID) values (470, 'Avelinha', 80);
insert INTO CITY (City_ID, City_Name, Country_ID) values (471, 'Daiyue', 81);
insert INTO CITY (City_ID, City_Name, Country_ID) values (472, 'Butungan', 82);
insert INTO CITY (City_ID, City_Name, Country_ID) values (473, 'Ledeč nad Sázavou', 83);
insert INTO CITY (City_ID, City_Name, Country_ID) values (474, 'Bélel', 84);
insert INTO CITY (City_ID, City_Name, Country_ID) values (475, 'Nzega', 85);
insert INTO CITY (City_ID, City_Name, Country_ID) values (476, 'Shekou', 86);
insert INTO CITY (City_ID, City_Name, Country_ID) values (477, 'Emiliano Zapata', 87);
insert INTO CITY (City_ID, City_Name, Country_ID) values (478, 'Damiao', 88);
insert INTO CITY (City_ID, City_Name, Country_ID) values (479, 'Lorena', 89);
insert INTO CITY (City_ID, City_Name, Country_ID) values (480, 'Kalpin', 90);
insert INTO CITY (City_ID, City_Name, Country_ID) values (481, 'Trenggulunan', 91);
insert INTO CITY (City_ID, City_Name, Country_ID) values (482, 'Bressuire', 92);
insert INTO CITY (City_ID, City_Name, Country_ID) values (483, 'Xiongzhou', 93);
insert INTO CITY (City_ID, City_Name, Country_ID) values (484, 'Koubia', 94);
insert INTO CITY (City_ID, City_Name, Country_ID) values (485, 'Cinunjang', 95);
insert INTO CITY (City_ID, City_Name, Country_ID) values (486, 'Paraíso', 96);
insert INTO CITY (City_ID, City_Name, Country_ID) values (487, 'Shiyu', 97);
insert INTO CITY (City_ID, City_Name, Country_ID) values (488, 'Savonranta', 98);
insert INTO CITY (City_ID, City_Name, Country_ID) values (489, 'Haparanda', 99);
insert INTO CITY (City_ID, City_Name, Country_ID) values (490, 'Garzón', 100);
insert INTO CITY (City_ID, City_Name, Country_ID) values (491, 'El Puerto', 101);
insert INTO CITY (City_ID, City_Name, Country_ID) values (492, 'Tianmen', 102);
insert INTO CITY (City_ID, City_Name, Country_ID) values (493, 'Mokwa', 103);
insert INTO CITY (City_ID, City_Name, Country_ID) values (494, 'Düsseldorf', 104);
insert INTO CITY (City_ID, City_Name, Country_ID) values (495, 'Masachapa', 105);
insert INTO CITY (City_ID, City_Name, Country_ID) values (496, 'Xinkaikou', 106);
insert INTO CITY (City_ID, City_Name, Country_ID) values (497, 'Cogon', 107);
insert INTO CITY (City_ID, City_Name, Country_ID) values (498, 'San Felipe Old', 108);
insert INTO CITY (City_ID, City_Name, Country_ID) values (499, 'Huadi', 109);
insert INTO CITY (City_ID, City_Name, Country_ID) values (500, 'Shen’ao', 110);